### ISSUE TITLE
Error to run config

### ISSUE THREAD

**Issue by thiagolcks** [SpiderLabs/ModSecurity-nginx#10]
Hi,

I'm trying to compile it to use as a dynamic module but I'm getting these errors running ./config:

```
./config: line 23: [: =: unary operator expected
./config: line 25: [: =: unary operator expected
./config: line 31: auto/feature: No such file or directory
./config: line 33: [: =: unary operator expected
./config: line 64: [: =: unary operator expected
```

I'm using Ubuntu 14.04. I couldn't find any documentation explaining how to do it.

Cheers,

**Comment by zimmerle** [comment]
Hi @thiagolcks,

That is not the right way to compile this nginx add-on. Please look at here:

https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes
