### ISSUE TITLE
Possibly missing libraries at link time?

### ISSUE THREAD

**Issue by ivanbaldo** [SpiderLabs/ModSecurity-nginx#101]
I am building libmodsecurity statically with --disable-shared, then building the Nginx connector and then adding the connector to Nginx.
The linking fails at the end of the compilation of Nginx.
To fix it, I did this:
```sh
sed -i 's/-lmodsecurity/-lmodsecurity -lm -lstdc++ -lyajl -lxml2 -lcurl -lGeoIP -lfuzzy/g' \
  ModSecurity-nginx/config
```
Of course this is not the correct solution, just mentioning what I did.
I guess the correct way would be to use pkg-config or something else.
I guess most people don't compile libmodsecurity statically but in my case it simplifies things.
Thanks for looking into this!

**Comment by zimmerle** [comment]
@ivanbaldo we may want to link against the .la file not really to the .so one. In any case,  are you working with any other 'static' library that behaves differently?

**Comment by ivanbaldo** [comment]
Hello, thanks for your reply!
No, I am only adding ModSecurity to Nginx.
But if I remember correctly from long time ago, the way to go is to use pkg-config and declare in it the dependencies of the built library.
Doesn't matter if shared or static or both, the dependencies should be specified for pkg-config and the programs (in this case the connector) should use pkg-config to get the CFLAGS and LDFLAGS.
This is how "I think" it works, but I am no expert :-( .

**Comment by zimmerle** [comment]
pkg-config is still an option but we are no only limited by its support. We recommend you to try to link against the .la file. That should do it for now.
