### ISSUE TITLE
Exlusion Rules

### ISSUE THREAD

**Issue by gnopo** [SpiderLabs/ModSecurity-nginx#111]
I need to create a rule that only match certain parameters....and allow that traffic go thru....but is the traffic does no match the rules...i want to block it....
How can I do that ??

**Comment by victorhora** [comment]
Hi @gnopo,

This issue tracking is more dedicated to issues or questions more specific to the Nginx-connector for libModSecurity, which I'm afraid is not the case for this issue.

That being said, you can try looking at the [doc resources provided at modsecurity.org](https://www.modsecurity.org/documentation.html). More specifically the [Reference Manual](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29) may be of great help alongside the [Practical Rule Writing section of the ModSecurity Handbook](https://books.google.ca/books?id=HnQl5OVtOYgC&pg=PA178&lpg=PA178&dq=%22Practical+Rule+Writing%22&source=bl&ots=0FmqVaDfLm&sig=2Hcl0VwEX57i46CooWzqv5uj4JI&hl=en&sa=X&ved=0ahUKEwjo__bft-PbAhXB24MKHQzIDL8Q6AEIKTAA#v=onepage&q=%22Practical%20Rule%20Writing%22&f=false).

If you still have questions, please try to provide as much detail as possible on what you're trying to accomplish, ideally with examples of the request line, parameters and etc that you're trying to block or pass through and post them on the appropriate mailing list (e.g. [mod-security-users](https://sourceforge.net/p/mod-security/mailman/mod-security-users/)) or on ModSecurity's issue tracking.

Thanks!
