### ISSUE TITLE
Directive "modsecurity_rules" is not working if it's defined in multiple 'server'

### ISSUE THREAD

**Issue by oleg9301** [SpiderLabs/ModSecurity-nginx#114]
Hello guys!

I have next config: two or more multiple directive "server" and i want disable or "DetectionOnly" for first "server" and "On" for second, third and other:
server = directive in nginx (Context)

versions:
```
nginx version: nginx/1.15.0
ModSecurity-nginx 1.0.0
Modsecurity 3.0.2
```

cat nginx.conf
```
load_module modules/ngx_http_modsecurity_module.so;

***

http {
        modsecurity on;
        modsecurity_rules_file /etc/nginx/modsec/main.conf;

        *****

	include    /etc/nginx/conf.d/*.http.conf;
}
```

cat /etc/nginx/conf.d/*.http.conf

```
server {
        *****
	modsecurity_rules '
		SecRuleEngine Off';
        *****
	location / {
        *****
	}
}
server {
        *****
	modsecurity_rules '
		SecRuleEngine On';
        *****
	location / {
        *****
	}
}

```
cat modsec/main.conf
```
Include "/etc/nginx/modsec/owasp-modsecurity-crs/crs-setup.conf"
Include "/etc/nginx/modsec/modsecurity.conf"
Include "/etc/nginx/modsec/owasp-modsecurity-crs/rules/*.conf"
```

cat modsec/modsecurity.conf

```
SecRuleEngine On
SecRemoteRules
 ***
```

Is it possible in current version nginx connector? Or I can only On/Off modsecurity for all "servers"

**Comment by victorhora** [comment]
Hi @oleg9301,

I'm not sure if the different Nginx configuration contexts are all working as expected at this moment. See #110 and https://github.com/SpiderLabs/ModSecurity-nginx/issues/76#issuecomment-365240170.

Have you tried with the runtime directives such as [ctl:ruleEngine=off](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#ctl)?

**Comment by zimmerle** [comment]
Hi @oleg9301,

ModSecurity tries to mimic the semantic of nginx in terms of merging the configurations. That said, the behavior of ModSecurity should be the same as any other conf directive. If not, please re-open the issue. In the meanwhile should be safe to run ``` ctl:ruleEngine=off``` as suggested by @victorhora.
