### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by BP9906** [SpiderLabs/ModSecurity-nginx#118]
I have a small PHP farm of nginx servers and php-fpm with ModSecv3 installed. Over the past several days, I noticed that Nginx worker processes are consuming 3GB of memory per worker (work is auto and thus is using 4 for me) and thus running out of memory and OOM killer kills the worker and the process starts over.  I disable ModSecurity (ie modsecurity off) and memory usage doesnt increase. I've only been running in detection only mode for these servers.  I suspect that its a memory leak because of the growing memory requirement and this issue only started since installing modsecurity with this Nginx/PHP farm. Nginx normally stays below 1GB memory usage.

"ps aux --sort -rss" is how i'm viewing memory using.

**Comment by victorhora** [comment]
@BP9906 make sure you're using the latest codebase from master for both ModSecurity-nginx and ModSecurity. There's a number of recent improvements in case you're running libModSecurity 3.0.0, 3.0.1 or 3.0.2.

I'm marking this as duplicate as memory management issues are already being discussed here: #73 / #79, #115. Please follow up your observations on these issues. Thanks.
