### ISSUE TITLE
ModSecurity Segmentation Fault with Nginx 1.15.1 when using modsecurity_rules_file directive

### ISSUE THREAD

**Issue by femrits** [SpiderLabs/ModSecurity-nginx#119]
i've installed ModSecurity 3 following the instructions in https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes-for-v3.x (only changed the bison library source to http://www.rpmfind.net/linux/fedora/linux/releases/28/Everything/x86_64/os/Packages/b/bison-3.0.4-9.fc28.x86_64.rpm) and compiled nginx 1.15.1 with it.

After configuring everything and running nginx -T before starting the server it only shows "Segmentation Fault" as a result. if i disable ModSecurity rules (#modsecurity_rules_file), the server works perfectly. Can you help me?

This is my server info:

> OS: centos-release-7-5.1804.el7.centos.2.x86_64
> SELINUX: Yes
> Nginx -V:
nginx version: nginx/1.15.1 (CentOS)
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) 
built with OpenSSL 1.1.0h  27 Mar 2018
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --build=CentOS --builddir=nginx-1.15.1 --with-compat --with-debug --with-file-aio --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_geoip_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_xslt_module --with-mail --with-mail_ssl_module --with-openssl=/nginx-1.15.1/openssl-1.1.0h --with-pcre=/nginx-1.15.1/pcre-8.42 --with-pcre-jit --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-threads --with-zlib=/nginx-1.15.1/zlib-1.2.11 --add-module=/nginx-1.15.1/ngx_brotli --add-module=/nginx-1.15.1/incubator-pagespeed-ngx-1.13.35.2-stable --add-module=/nginx-1.15.1/ngx_devel_kit --add-module=/nginx-1.15.1/set-misc-nginx-module --add-module=/nginx-1.15.1/ModSecurity-nginx
> 
> php72 --version:
> PHP 7.2.8 (cli) (built: Jul 17 2018 08:41:40) ( NTS )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
>     with Zend OPcache v7.2.8, Copyright (c) 1999-2018, by Zend Technologies

**Comment by zimmerle** [comment]
Hi @femrits,

It sounds like you have something weird in your environment. Did you had the chance to execute ModSecurity's _make check_ after the compilation process? If not, please do. I will close this for now, feel free to re-open in case you did not sorted it out.
