### ISSUE TITLE
Problem with ModSecurity no support JSON

### ISSUE THREAD

**Issue by alterego2004** [SpiderLabs/ModSecurity-nginx#120]
A good day! I have reverse proxy nginx with modsecurity
after send POST http I have error

ModSecurity: JSON support was not enabled [hostname ""] [uri "/postComment"] [unique_id "0dAcAcxcAcncABABAYAcAcAc"]
To fix  it I rebuild modsecurity with **LibYAJL** library
git clone git://github.com/lloyd/yajl
tar  yajl
cd yajl/
   ./configure
    make
   make install
   ldconfig
cd Modsecurity/
./configure --with-yajl="/usr/local/lib /usr/local"
 make
 make install
ln -s /usr/local/share/pkgconfig/yajl.pc /usr/share/pkgconfig/yajl.pc
after that steps I have same error!
How I can fix it?

**nginx -V**
nginx version: nginx/1.10.3 (Ubuntu)
built with OpenSSL 1.0.2g  1 Mar 2016
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_addition_module --with-http_dav_module --with-http_geoip_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_v2_module --with-http_sub_module --with-http_xslt_module --with-stream --with-stream_ssl_module --with-mail --with-mail_ssl_module --with-threads

 **uname -a**
Linux free 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

With Best Regards!

**Comment by victorhora** [comment]
Hi @alterego2004 

I think you're not pointing the _--with-yajl_ option to the correct path. As you have already _make install_ YAJL the _configure_ script should be able to detect it automatically so you could omit the _--with-yajl_ option and you should see something like when running _./configure_: ```configure: using YAJL v2.1.1```

At the end of the script you should see a summary which should show YAJL options  as highlighted below:

```
ModSecurity - v3.0.2-64-ga3980bb for Linux

 Mandatory dependencies
   + libInjection                                  ....v3.0.2-64-ga3980bb
   + SecLang tests                                 ....a3980bb

 Optional dependencies
   + GeoIP/MaxMind                                 ....found
      * (GeoIP) v1.6.2
         -lGeoIP , -I/usr/include/
   + LibCURL                                       ....found v7.38.0
      -L/usr/lib/x86_64-linux-gnu -lcurl,  -DWITH_CURL_SSLVERSION_TLSv1_2 -DWITH_CURL
```
   **+ YAJL                                          ....found v2.1.0
      -lyajl , -DWITH_YAJL -I/usr/include/yajl**
```
   + LMDB                                          ....not found
   + LibXML2                                       ....found v2.9.1
      -lxml2, -I/usr/include/libxml2 -DWITH_LIBXML2
   + SSDEEP                                        ....not found
   + LUA                                           ....found v503
      -llua5.3 -L/usr/lib/x86_64-linux-gnu/, -DWITH_LUA -I/usr/include/lua5.3

 Other Options
   + Test Utilities                                ....enabled
   + SecDebugLog                                   ....enabled
   + afl fuzzer                                    ....disabled
   + library examples                              ....enabled
   + Building parser                               ....disabled
   + Treating pm operations as critical section    ....disabled
```

If this is not what you're getting, try specifying the _--with-yajl_ with the correct path pointing to the YAJL header files (.h) like /usr/include/yajl or /usr/local/include/yajl or even to the path where you compiled YAJL (yajl/build/yajl-2.1.1).

**Comment by victorhora** [comment]
As this question is more specific with libModSecurity and not related with the ModSecurity-nginx connector I will be closing it. If you still have problems, please open the issue on the appropriate bug tracker for libModSecurity here: https://github.com/SpiderLabs/ModSecurity/issues
