### ISSUE TITLE
Per-location rule exclusion

### ISSUE THREAD

**Issue by Onepamopa** [SpiderLabs/ModSecurity-nginx#123]
When nginx is configured as reverse-proxy with a single location / { } (which is all most people really need), the only way to exclude a rule in for example /wp-admin/admin-ajax.php is to create yet another location with proxy_pass, headers and so forth, and place:
modsecurity on;
modsecurity_rules '
SecRuleRemoveById XXXXXX
';

This is kind of inconvenient.

Are there any "global" config variables planned (TBI/TBD) that would be able to do this in a way like: modsecurity_exclude /path/to/something SecRuleRemoveById XXXXXX;

Regards,
D

**Comment by zimmerle** [comment]
Hi @Onepamopa,

ModSecurity's directive **SecRuleRemoveById** is a directive like any other, it means that it can be loaded from a third party file without a problem. You just need to use the **include** directive.
