### ISSUE TITLE
Failed compilation after new commits (October 29, 2018)

### ISSUE THREAD

**Issue by EcolaneAdam** [SpiderLabs/ModSecurity-nginx#128]
My ansible environment was compiling nginx and modsecurity ok this morning and then this afternoon it broke. It looks like the script was setup to pull from master branch of modsecurity-nginx

This is the error generated:
objs/addon/src/ngx_http_modsecurity_module.o: In function `ngx_http_modsecurity_create_ctx':
/usr/lib/modsecurity-nginx-connector/src/ngx_http_modsecurity_module.c:258: undefined reference to `msc_new_transaction_with_id'
collect2: error: ld returned 1 exit status
make[1]: *** [objs/nginx] Error 1
make[1]: Leaving directory `/root/nginx-1.13.4'

This is the compilation command run, if done manually:
cd /root/nginx-1.13.4 && ./configure --user=www-data --group=www-data --prefix=/opt/nginx --with-debug --with-ipv6 --with-http_ssl_module --with-http_gzip_static_module --with-http_stub_status_module --with-cc-opt=-Wno-error --with-ld-opt= --add-module=/usr/lib/modsecurity-nginx-connector --add-module=/opt/ecolane/rails/.rvm/gems/ruby-2.3.1/gems/passenger-5.0.28/src/nginx_module && make && make install

Is there an older version I can pull against? As mentioned, currently it was setup to pull against Master.
  git:
    repo: 'https://github.com/SpiderLabs/ModSecurity-nginx.git'
    dest: '/usr/lib/modsecurity-nginx-connector'
    version: master
    force: true

**Comment by EcolaneAdam** [comment]
Thanks for the feedback.

I adjusted my ansible code to pull tagged v1.0.0 instead of master and it fixed the issue.

I will run your current code updates through change management for next version of ours.

**Comment by tanjuu** [comment]
Even i got this error:
nginx: [emerg] dlopen() "/usr/local/nginx/modules/ngx_http_modsecurity_module.so" failed (/usr/local/nginx/modules/ngx_http_modsecurity_module.so: undefined symbol: msc_new_transaction_with_id) in /usr/local/nginx/conf/dynamic-modules.conf:1
nginx: configuration file /usr/local/nginx/conf/nginx.conf test failed

Kindly help me how can i resolve this issue

**Comment by victorhora** [comment]
@tanjuu 

Please read response just above your comment: https://github.com/SpiderLabs/ModSecurity-nginx/issues/128#issuecomment-434104371
 
> The problem is probably due to the [recently introduced](https://github.com/SpiderLabs/ModSecurity-nginx/commit/ad5ab17a823ed9e1347cb643ad08d2cbb7a918ba) msc_new_transaction_with_id() only being available on a newer version of libModSecurity (as of [SpiderLabs/ModSecurity@4dd2812](https://github.com/SpiderLabs/ModSecurity/commit/4dd28127577eca0bf854db5c134a4134db6ff1ec) to be more specific).
> 
> So I suggest that you upgrade your current libModSecurity codebase and you should be fine.

Follow the same steps and you should be fine.

**Comment by tanjuu** [comment]
Thanks for the feedback

issue is resolved now
