### ISSUE TITLE
Can Nginx-Modsecurity surport senting logs to Syslog

### ISSUE THREAD

**Issue by meigea** [SpiderLabs/ModSecurity-nginx#135]
i know that nginx can suport logging to syslog, and is there some way that can do this that sent to syslog except deploy a syslog-client to sent log.

**Comment by victorhora** [comment]
@meigea as far as I can recall, you can tune your log entries to be written to Nginx error_log and being so, they could be logged to syslog by tuning Nginx to do it.

I don't think the audit_log / debug_logs have native support for sending it syslog. But you could use the HTTPS transport by setting the [SecAuditLogType](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecAuditLogType) to "HTTPS" which allows sending the logs directly to a remote (or localhost) server without the usage of a log collector such as MLogC (2.x). See [#1839](https://github.com/SpiderLabs/ModSecurity/issues/1839).

**Comment by meigea** [comment]
@victorhora Thank you very much , i think you have helped me.
