### ISSUE TITLE
Sends file instead of rendering webpage when using http2

### ISSUE THREAD

**Issue by Jumbledwords** [SpiderLabs/ModSecurity-nginx#137]
I'm running Ubuntu 18.04 LTS with Nginx 1.15.6. 

```
server { 
    listen 80 http2 default_server; 
    listen [::]:80 http2 default_server ipv6only=on; 
...}
```

The above causes the server to prompt me to accept a download when I visit the domain, instead of rendering the website. Removing http2 allows the server to render the website again. 

How do I fix this issue?

**Comment by zimmerle** [comment]
Hi @Jumbledwords,

It only happens when ModSecurity is on?

**Comment by zimmerle** [comment]
Hi @Jumbledwords,

Without further details will be very hard to help you. I am assuming you figure out what was wrong and solve the problem. Please share your experience, so others can learn from it.

I am going to mark this issue as closed. But it is still editable.
