### ISSUE TITLE
Error while configuring nginx with modsecurity dynamic module

### ISSUE THREAD

**Issue by AnnuA** [SpiderLabs/ModSecurity-nginx#138]
Downloaded the latest Modsecurity-nginx code.
Configured the nginx 1.14.0 source code using below command
sudo ./configure --with-compat --add-dynamic-module=../ModSecurity-nginx

Got the below error.
../ModSecurity-nginx/src/ngx_http_modsecurity_module.c: **In function ‘ngx_http_modsecurity_create_ctx’:
../ModSecurity-nginx/src/ngx_http_modsecurity_module.c:258:35: error: implicit declaration of function ‘msc_new_transaction_with_id’ [-Werror=implicit-function-declaration]**
         ctx->modsec_transaction = msc_new_transaction_with_id(cf->modsec, loc_cf->rules_set, (char *) s.data, r->connection->log);

Few months back I could successfully run this command. I compared the latest Modsecurity-nginx code with the previous one. There are some modifications in code in lines with the above error.
Is there a bug in the code or am I missing something.

**Comment by zimmerle** [comment]
Hi @AnnuA,

Please upgrade to the latest libModSecurity: https://github.com/SpiderLabs/ModSecurity/releases/tag/v3.0.3
