### ISSUE TITLE
Question - How can I change the default error code (403) in ModSecurity

### ISSUE THREAD

**Issue by vikas027** [SpiderLabs/ModSecurity-nginx#140]
Hey All,

By default, ModSecurity blocks something with an error code 403. In our environment, we want to change this code to something else (say 455 for example).

As per docs, it can be done in the _RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf_ file but I could not figure it out how to do it.

I know it can be done per rule ID, but again not sure how to make it a default globally across ModSecurity.

Thanks in advance.

**Comment by victorhora** [comment]
Hi @vikas027 

To change this per rule, you should use the [status](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#status) action.

If you want globally, you need to set it as a [SecDefaultAction](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecDefaultAction).

But if you're using the CRS, you might need to change it directly on the CRS configuration files.

Hope that helps.
