### ISSUE TITLE
nginx doesn't work when load CDM

### ISSUE THREAD

**Issue by n0sign4l** [SpiderLabs/ModSecurity-nginx#147]
Hi!
I have followed point to point this tutorial but I encounter some issue... (https://www.nginx.com/blog/compiling-and-installing-modsecurity-for-open-source-nginx/)

When I load the NGINX ModSecurity Connector Dynamic Module and add the modsecurity and modsecurity_rules_file directives to the NGINX configuration to enable ModSecurity my nginx webserver doesn't work anymore.
running `journalctl -xe` I get:
Subject: Unit nginx.service has begun start-up
-- Defined-By: systemd
-- 
-- Unit nginx.service has begun starting up.
Dec 28 00:15:25 user nginx[1593]: nginx: [emerg] dlopen() "/usr/share/nginx/modules/ngx_http_modsecurity_module.so" failed (/usr/share/nginx/modul
Dec 28 00:15:25 user nginx[1593]: nginx: configuration file /etc/nginx/nginx.conf test failed
Dec 28 00:15:25 user systemd[1]: nginx.service: Control process exited, code=exited status=1
Dec 28 00:15:25 user systemd[1]: nginx.service: Failed with result 'exit-code'.
Dec 28 00:15:25 user systemd[1]: Failed to start A high performance web server and a reverse proxy server.

Can you help me?
Where I got wrong?
Thanks

**Comment by zimmerle** [comment]
Hi @n0sign4l,

It seems like the ```ngx_http_modsecurity_module.so``` is not installed in the directory that it suppose to be. There was any error during the compilation process? Is this file was ever generated?

**Comment by n0sign4l** [comment]
Running the command `locate ngx_http_modsecurity_module.so` nothing came up like if the file is not present in the server.. During the build process I didn't see any problem. How should I proceed?
Thx,

Leonardo 'n0sign4l' Porpora

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Il venerdì, dicembre 28, 2018 1:52 AM, Felipe Zimmerle <notifications@github.com> ha scritto:

**Comment by n0sign4l** [comment]
No, I have found it, it's in /root/ModSecurity/nginx-1.14.0/objs/ngx_http_modsecurity_module.so is it well located?

**Comment by n0sign4l** [comment]
The file is in /etc/nginx/modules/ngx_http_modsecurity_module.so
i get this error
-- Unit nginx.service has begun starting up.
Dec 28 11:35:38 user nginx[20600]: nginx: [emerg] dlopen() "/usr/share/nginx/modules/ngx_http_modsecurity_module.so" failed (/usr/share/nginx/modules/ngx_http_modsecurity_module.so: cannot open shared object file: No such file or directory) in /etc/nginx/nginx.conf:2
Dec 28 11:35:38 user nginx[20600]: nginx: configuration file /etc/nginx/nginx.conf test failed
Dec 28 11:35:38 user systemd[1]: nginx.service: Control process exited, code=exited status=1
Dec 28 11:35:38 user systemd[1]: nginx.service: Failed with result 'exit-code'.
Dec 28 11:35:38 user systemd[1]: Failed to start A high performance web server and a reverse proxy server.
-- Subject: Unit nginx.service has failed

**Comment by zimmerle** [comment]
Can you share the output of ```ldd```?

```
$ ldd /etc/nginx/modules/ngx_http_modsecurity_module.so
```

**Comment by leonardoporp** [comment]
I have the same issue can you help me?

**Comment by zimmerle** [comment]
Hi @n0sign4l,

I see now that your nginx is trying to load the module in a different directory. You may want to move the file to ```/usr/share/nginx/modules/ngx_http_modsecurity_module.so``` or use the full path to load the module in nginx configuration.

**Comment by zimmerle** [comment]
@leonardoporp if you have the exactly same problem, the suggestions above should work for you as well. If not, please file a new issue.

**Comment by sergiorla** [comment]
HI @zimmerle im having a similar problem im hoping you can help me with. I added the full path but i get the following error:

`nginx: [emerg] module "/etc/nginx/modules/ngx_http_modsecurity_module.so" is not binary compatible in /etc/nginx/nginx.conf:6`

this is the output i get when i run `ldd`

```
$ ldd /etc/nginx/modules/ngx_http_modsecurity_module.so
	linux-vdso.so.1 (0x00007fff209c3000)
	libmodsecurity.so.3 => /usr/local/modsecurity/lib/libmodsecurity.so.3 (0x00007f783abe3000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f783a7f2000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f783a5ea000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f783a378000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f7839fef000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7839c51000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f783b212000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7839a39000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f783981a000)
```

Thank you!

**Comment by Mar1on1** [comment]
Hello,
I followed the manual to the letter but I throw the following error
nginx: [emerg] dlopen() "/usr/share/nginx/modules/ngx_http_modsecurity_module.so" failed (/usr/share/nginx/modules/ngx_http_modsecurity_module.so: cannot open shared object file: No such file or directory) in /etc/nginx/nginx.conf:5

additional to this send

ldd: /etc/nginx/modules/ngx_http_modsecurity_module.so: No such file or directory

don't create that file

**Comment by Mar1on1** [comment]
help me !!!

**Comment by barryguda-1** [comment]
Disable SELINUX that worked for me

**Comment by zimmerle** [comment]
@Mar1on1 please double check if **ngx_http_modsecurity_module.so** was generated, if not please share the related error message.

**Comment by coledeihs** [comment]
still not working for me.  that file is there

**Comment by johnjbateman** [comment]
I'm also seeing issues with this.  I upgraded to the CRS 3.3.0 and NGINX Plus does not load:

```
I0401 13:56:26.676724       1 main.go:257] Starting NGINX Ingress controller Version=1.10.1 GitCommit=ba03a73d
W0401 13:56:26.714428       1 main.go:296] The '-use-ingress-class-only' flag will be deprecated and has no effect on versions of kubernetes >= 1.18.0. Processing ONLY resources that have the 'ingressClassName' field in Ingress equal to the class.
W0401 13:56:26.720397       1 warnings.go:70] networking.k8s.io/v1beta1 IngressClass is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 IngressClassList
2021/04/01 13:56:26 [emerg] 11#11: dlopen() "/etc/nginx/modules/ngx_http_modsecurity_module.so" failed (/etc/nginx/modules/ngx_http_modsecurity_module.so: cannot open shared object file: No such file or directory) in /etc/nginx/nginx.conf:9
nginx: [emerg] dlopen() "/etc/nginx/modules/ngx_http_modsecurity_module.so" failed (/etc/nginx/modules/ngx_http_modsecurity_module.so: cannot open shared object file: No such file or directory) in /etc/nginx/nginx.conf:9
F0401 13:56:30.794283       1 manager.go:284] Could not get newest config version: could not get expected version: 0 after 4000 ms
```

**Comment by zimmerle** [comment]
@johnjbateman can you paste the output of ```ldd /etc/nginx/modules/ngx_http_modsecurity_module.so``` here?

**Comment by johnjbateman** [comment]
> @johnjbateman can you paste the output of `ldd /etc/nginx/modules/ngx_http_modsecurity_module.so` here?

In my case, this was an issue where the file actually did not exist.  I made sure I downloaded mod sec and all was well.

**Comment by zimmerle** [comment]
@johnjbateman did you got any error during the build process? have you installed ModSecurity connector?

**Comment by johnjbateman** [comment]
no, i didnt get an error building.  just when running the container.  My issue was i missed actually downloading and installing modsecurity

**Comment by zimmerle** [comment]
@johnjbateman I am not were of the details for nginx plus; @defanator may be able to help you better on this issue.

**Comment by johnjbateman** [comment]
you mis-understood.  My issue is resolved @zimmerle

**Comment by zimmerle** [comment]
> you mis-understood. My issue is resolved @zimmerle

oh, I see. my bad.

**Comment by AliAlievALive** [comment]
ldd /etc/nginx/modules/ngx_http_modsecurity_module.so
        linux-vdso.so.1 (0x00007ffd249cd000)
        libmodsecurity.so.3 => not found
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f16dde36000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f16de009000)

Help me please...
