### ISSUE TITLE
compiling issues on Centos 6.8

### ISSUE THREAD

**Issue by receiving2006** [SpiderLabs/ModSecurity-nginx#154]
libmodsecurity has been installed on /usr/local/modcurity, when use --add-module=../ModSecurity-nginx, the fatal error comes up.

checking for ModSecurity library ... not found
checking for ModSecurity library in /usr/local/modsecurity ... not found
 ./configure: error: ngx_http_modsecurity_module requires the ModSecurity library.

after using export MODSECURITY_INC="/opt/pkg/ModSecurity/headers/" and export MODSECURITY_LIB="/opt/pkg/ModSecurity/src/.libs/"
 The error still come here.
adding module in ../ModSecurity-nginx
checking for ModSecurity library in "/opt/pkg/ModSecurity/src/.libs/" and "/opt/pkg/ModSecurity/headers/" (specified by the MODSECURITY_LIB and MODSECURITY_INC env) ... not found
 ./configure: error: ngx_http_modsecurity_module requires the ModSecurity library.

Can anybody help me? it frustrated me for weeks.

**Comment by zimmerle** [comment]
Hi @receiving2006,

You have to point  MODSECURITY_INC and MODSECURITY_LIB towards to installation directory of your ModSecurity. If you have it installed at `/usr/local/modsecurity` that will be:

- export MODSECURITY_LIB="/usr/local/modsecurity/lib/"
- export MODSECURITY_INC="/usr/local/modsecurity/include/"

**Comment by receiving2006** [comment]
Hi @zimmerle,
Many many thanks for your replying. I have ever tried it yet, but still not works, error as below,
adding module in /opt/pkg/ModSecurity-nginx/
checking for ModSecurity library in "/usr/local/modsecurity/lib/" and "/usr/local/modsecurity/include/" (specified by the MODSECURITY_LIB and MODSECURITY_INC env) ... not found
 ./configure: error: ngx_http_modsecurity_module requires the ModSecurity library.

it confused me, I have to post the request, any ideas? thanks in advance.

**Comment by receiving2006** [comment]
/usr/local/modsecurity/
├── bin
│   └── modsec-rules-check
├── include
│   └── modsecurity
│       ├── actions
│       │   └── action.h
│       ├── anchored_set_variable.h
│       ├── anchored_variable.h
│       ├── audit_log.h
│       ├── collection
│       │   ├── collection.h
│       │   └── collections.h
│       ├── debug_log.h
│       ├── intervention.h
│       ├── modsecurity.h
│       ├── reading_logs_via_rule_message.h
│       ├── rule.h
│       ├── rule_message.h
│       ├── rules_exceptions.h
│       ├── rules.h
│       ├── rules_properties.h
│       ├── transaction.h
│       ├── variable_origin.h
│       └── variable_value.h
└── lib
    ├── libmodsecurity.a
    ├── libmodsecurity.la
    ├── libmodsecurity.so -> libmodsecurity.so.3.0.3
    ├── libmodsecurity.so.3 -> libmodsecurity.so.3.0.3
    ├── libmodsecurity.so.3.0.3
    └── pkgconfig
        └── modsecurity.pc
