### ISSUE TITLE
libmodsecurity and ModSecurity-nginx have to be installed on the same machine?

### ISSUE THREAD

**Issue by lhy0726** [SpiderLabs/ModSecurity-nginx#156]
hi, 
     may i install libmodsecurity on nginxA, and install ModSecurity-nginx on nginxB and nginxC ?

     is there a way to realize similar function ?

**Comment by victorhora** [comment]
@lhy0726, I think this could be possible using something like an NFS mounted filesystem where the compiled shared library (.so) for libModSecurity is stored and then having your "client" Nginx' instances loading the libraries at runtime. 

That being said I haven't tested this scenario and there might be some other cleverer/simpler approach for what you need. 

I'm closing this issue, but for the benefit of others, please let us know what you find out. Thanks.
