### ISSUE TITLE
How to add rule for exclude multiple app's exclusion rules

### ISSUE THREAD

**Issue by ckattarrap** [SpiderLabs/ModSecurity-nginx#157]
Hello Team,

I"m running wordpres, magento on same server.
and I made default exclusion rules for wordpress, magento.
Sine I'm running multiple applications on same server, I need to add rules for exclude default rules.

**EX: 
SecAction \
 "id:900130,\
phase:1,\
nolog,\
pass,\
t:none,\
setvar:tx.crs_exclusions_wordpress=1"**

Can you help me on this?

Regards,

Chandrasekhar

**Comment by victorhora** [comment]
@ckattarrap this GitHub project is more dedicated to issues or questions concerned with ModSecurity-nginx. Being so I would kindly ask you to direct issues or questions with the Core Rule Set to the [community project](https://github.com/SpiderLabs/owasp-modsecurity-crs). Thanks.
