### ISSUE TITLE
Feed back mod_security rule evaluation results into nginx keyval

### ISSUE THREAD

**Issue by absynth47215** [SpiderLabs/ModSecurity-nginx#158]
I was wondering if the following is possible or could be implemented with mod_security for nginx plus (or the open source version here):
1. If the attack threshold is reached for a specific remote IP address, use IPC or a special SecAction to insert that IP address into an nginx shared memory zone / keyval
2. On the next attack by that IP, mod_security doesn't need to be called but it's 403'ed directly from within nginx (dynamic blacklisting API example from nginx docs)
3. Massive performance gains by not having to route the request through mod_security's ruleset

What would be a way to do this? Is it possible at all?

**Comment by zimmerle** [comment]
Hi @absynth47215,

There is the possibility to have ModSecurity feeding a script with data (i.e. Lua). This script can populate any structure that you may want. You can also extend the ModSecurity code to accomplish such a goal. 

There is no built-in function to do so.
