### ISSUE TITLE
dpkg-shlibdeps: error: no dependency information found for /usr/local/modsecurity/lib/libmodsecurity.so.3

### ISSUE THREAD

**Issue by olekstumedia** [SpiderLabs/ModSecurity-nginx#16]
Hmm looks like incompatibility with Ubuntu16 =(( not sure how to work around.

I am rebuild nginx with mod_security and nginx.
  
root@host:~/rebuildnginx/nginx-1.11.4ll ../
total 1084
drwxr-xr-x  5 root root   4096 Sep 14 14:32 ./
drwx------ 13 root root   4096 Sep 14 14:34 ../
drwxr-xr-x  3 root root   4096 Sep 14 13:35 modsec/
drwxr-xr-x 11 root root   4096 Sep 14 15:07 nginx-1.11.4/
-rw-r--r--  1 root root 133672 Sep 13 12:47 nginx_1.11.4-1~xenial.debian.tar.xz
-rw-r--r--  1 root root   1843 Sep 13 12:47 nginx_1.11.4-1~xenial.dsc
-rw-r--r--  1 root root 949793 Sep 13 12:46 nginx_1.11.4.orig.tar.gz
drwxr-xr-x  3 root root   4096 Sep 14 13:32 pagespeed/

 dh_compress
   dh_fixperms
   debian/rules override_dh_strip
make[1]: Entering directory '/root/rebuildnginx/nginx-1.11.4'
dh_strip --dbg-package=nginx-dbg
make[1]: Leaving directory '/root/rebuildnginx/nginx-1.11.4'
   dh_makeshlibs
   dh_shlibdeps
dpkg-shlibdeps: error: no dependency information found for /usr/local/modsecurity/lib/libmodsecurity.so.3 (used by debian/nginx/usr/sbin/nginx-debug)
Hint: check if the library actually comes from a package.
dh_shlibdeps: dpkg-shlibdeps -Tdebian/nginx.substvars debian/nginx/usr/sbin/nginx debian/nginx/usr/sbin/nginx-debug returned exit code 2
debian/rules:64: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: debian/rules binary gave error exit status 2

**Comment by olekstumedia** [comment]
Trying this workaround

https://github.com/linuxmint/nemo/issues/1079#issuecomment-195934523

adding bellow code to debian/rules

override_dh_shlibdeps:
        dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info

_It is necessary to insert a TAB instead of spaces before "dh_shlibdeps ..."_

**Comment by olekstumedia** [comment]
Looks like worked

**Comment by adrelanos** [comment]
I am having this issue when using static module. Workaround is OK but a workaround is not a fix. Could you re-open please?

**Comment by leonardocxavier** [comment]
Add this code on debug mode, and are fixed problem.
Change line:
        dh_shlibdeps -a
For ( removing -a )
        dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info
