### ISSUE TITLE
Printing arbitrary logs at the audit file.

### ISSUE THREAD

**Issue by marcioaso** [SpiderLabs/ModSecurity-nginx#160]
First of all, good night.
I have been working at the configuration of the ModSecurity on nginx (not nginx+) to restrain DDOS attacks on my server.

I'm using CentOS 7, and I've installed correctly, since on ```LogDebugLevel 4``` it takes a 1Mb/s write rare like a storage psychopath (maybe not too correct, indeed).

My goal is to print (not block) ONLY the eligible requests to the audit log, basically to establish the metrics which will be used as the blocking rule.

Here is my configuration, (just the configs I've changed from the default):

**/etc/nginx/modsec/main.conf**
```
Include /etc/nginx/modsec/crs_setup.conf
SecAuditEngine On

# RULES
Include /etc/nginx/modsec/REQUEST-901-INITIALIZATION-no-block.conf
Include /etc/nginx/modsec/REQUEST-912-DOS-PROTECTION-no-block.conf

SecAuditLog /mnt/disks/data/var/log/modsecure/modsec_debug.log
SecAuditLog2 /mnt/disks/data/var/log/modsecure/modsec_debug2.log
SecAuditLogParts AB
SecAuditLogType concurrent
SecDebugLogLevel 3
```

**crs-setup.conf:**
```
SecAction \
 "id:900700,\
  phase:1,\
  nolog,\
  pass,\
  t:none,\
  setvar:'tx.dos_burst_time_slice=60',\
  setvar:'tx.dos_counter_threshold=2',\
  setvar:'tx.dos_block_timeout=30'"
# really low, I know.
```

**rules/REQUEST-901-INITIALIZATION.conf**
```
SecRule &TX:paranoia_level "@eq 0" \
    "id:901120,\
    phase:1,\
    pass,\
    nolog,\
    setvar:tx.paranoia_level=2"
```

**rules/REQUEST-912-DOS-PROTECTION.conf**
```commented from line 92 to 294```

```
nginx version: nginx/1.16.0
Virtualization: kvm
Operating System: CentOS Linux 7 (Core)
Kernel: Linux 3.10.0-862.9.1.el7.x86_64
Architecture: x86-64
```

I really don't know why the log is blank... BLANK! Nothing!
Maybe you guys can help with this. Please DO!

**Comment by victorhora** [comment]
>> My goal is to print (not block) ONLY the eligible requests to the audit log, basically to establish the metrics which will be used as the blocking rule.

I think you should be able to accomplish that by tuning your [SecAuditLogRelevantStatus](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecAuditLogRelevantStatus) directive?
