### ISSUE TITLE
No new releases since 2017

### ISSUE THREAD

**Issue by mtorromeo** [SpiderLabs/ModSecurity-nginx#162]
Hi,
I was wondering what's the status on new releases? Is 1.0.0 still to be considered the only "stable" release? No bug fixes?

The commits since the last release show multiple memory leaks fixed and ideally those would require a bugfix release without waiting a year or more.

Thanks

**Comment by victorhora** [comment]
Hi @mtorromeo, we would love to work on a new release but we are tied up to do another one right now. Ideally I would like to have a release before end of year. Fingers crossed :)

**Comment by mtorromeo** [comment]
That's good to hear, thanks! Any thoughts on releasing small bugfix releases more frequently in the future?

**Comment by zimmerle** [comment]
Hi @mtorromeo,

We are cooking a release and we are expecting to have it out of the door till the end of the year.
