### ISSUE TITLE
modsecurity + auth_request hang

### ISSUE THREAD

**Issue by chaoyun** [SpiderLabs/ModSecurity-nginx#163]
hi, Experts:
   I meet some issue why enable modSecurity plus with auth_request + http/2. 

   If a request with POST data, it will hang there. But "GET" method works well.

   There's a similar issue discussed in the https://github.com/kubernetes/ingress-nginx/issues/1932
   Disable modSecurity, it can work. Disable auth_request, it can also work.  Using http1.1 can work too. Only the combination of "modSecurity"+"auth_request"+http1.1 cannot work.
   Do you have any test for this case?

**Comment by chaoyun** [comment]
@defanator  Hi, I see you fixed this issue https://github.com/SpiderLabs/ModSecurity-nginx/pull/131. But with my latest test, seems it doesn't work.  In your testcase, I see you use http/2, right?

**Comment by defanator** [comment]
@chaoyun in connector tests we are using both HTTP/1 and HTTP/2 where applicable. I believe there were some TODO-marked tests specifically for HTTP/2, and auth_request can be one of those. I need to refresh my memory about that topic.

**Comment by chaoyun** [comment]
@defanator  Thanks for the reply.  Waiting for your update.  I checked the log in the modSecurity, seems it parsed the request, and there's no further log in both modSecurity and nginx. I don't know where it hung.

**Comment by zimmerle** [comment]
@chaoyun, @defanator 

Is this still an issue?

**Comment by defanator** [comment]
@zimmerle last time I checked there was an issue with HTTP/2. I'll try to pick some time to refresh this one.

**Comment by zimmerle** [comment]
Thank you @defanator. Warming up a release. Checking on what could be closed.

**Comment by dcherniv** [comment]
@defanator @zimmerle just got bit by this one too. Specifically kibana is completely broken with modsecurity + oauth proxy, which is a common combination people use

**Comment by victorhora** [comment]
The "nostale" tag has been set for this one and it's now reopened. We'll get to it when possible. Thank you.

**Comment by PaulCharlton** [comment]
see also:
https://github.com/kubernetes/ingress-nginx/issues/5723
https://github.com/SpiderLabs/ModSecurity/issues/2341

definitive workaround:
add `use-http2: false` to the Nginx listen block or k8s Nginx-ingress ConfigMap

At this point, we can write a unit test that sets conditions: (1) "POST + non-empty body", (2) side-car sub request Auth, (3) modsecurity enabled, (4) force HTTP2 + TLS session. iterate until the unit test works.

I imagine that since modsecurity is inspecting the request body, even when modsecurity `SecRulesEngine Off`, that it is somehow interfering with the state of the HTTP2 protocol handler.   I traced it down to a single byte in the payload, which is the blank line between the headers and the body is consumed by modsecurity, but not consumed when modsecurity is off.   For some reason as yet unknown to me, this impacts the sub-request to the Auth, but does not impact the upstream server request body.

**Comment by PaulCharlton** [comment]
@victorhora @zimmerle with the information above, this should be relatively easy to track down

**Comment by PaulCharlton** [comment]
this code looks really suspicious, and there are no unit tests configured with http2.
the phrase `r->main->count--;` can be invoked twice and there is no explanation for why it is Nginx version dependent.

`src/ngx_http_modsecurity_pre_access.c`

```
        r->request_body_in_single_buf = 1;
        r->request_body_in_persistent_file = 1;

        rc = ngx_http_read_client_request_body(r,
            ngx_http_modsecurity_request_read);
        if (rc == NGX_ERROR || rc >= NGX_HTTP_SPECIAL_RESPONSE) {
#if (nginx_version < 1002006) ||                                             \
    (nginx_version >= 1003000 && nginx_version < 1003009)
            r->main->count--;
#endif

            return rc;
        }
```
and
```
void
ngx_http_modsecurity_request_read(ngx_http_request_t *r)
{
    ngx_http_modsecurity_ctx_t *ctx;

    ctx = ngx_http_get_module_ctx(r, ngx_http_modsecurity_module);

#if defined(nginx_version) && nginx_version >= 8011
    r->main->count--;
#endif

    if (ctx->waiting_more_body)
    {
        ctx->waiting_more_body = 0;
        r->write_event_handler = ngx_http_core_run_phases;
        ngx_http_core_run_phases(r);
    }
}
```

**Comment by mtorromeo** [comment]
This is stille an issue. The nostale bug does not seem to work...

/reopen

**Comment by mtorromeo** [comment]
I noticed that in `tests/modsecurity-request-body-h2.t` there are already 4 tests that are specifically for this exact issue but are contained in a `TODO` block.

I removed the TODO and after running the tests with different versions of nginx I found out that the tests are failing with the stable release 1.18.0 but are passing with mainline nginx 1.19.6

**Comment by mtorromeo** [comment]
I just finished bisecting the nginx repository to find the exact commit that made the tests pass and this is it: https://github.com/nginx/nginx/commit/6c89d752c8ab3a3cc0832927484808b68153f8c4

I am not sure if a workaround is possible.

**Comment by defanator** [comment]
@mtorromeo thanks for digging into this! I have marked those tests as TODO and was going to specify the exact version where the issue has been resolved. Hopefully to find some time this week for that.

**Comment by mtorromeo** [comment]
I was hoping to find an easy fix and it's a bit disappointing to find out that it's actually a bug of nginx itself and that such a critical issue was not even backported to stable but what can you do...

**Comment by defanator** [comment]
@mtorromeo adjusted TODO versioning here: https://github.com/SpiderLabs/ModSecurity-nginx/commit/3f016fcf8545324c61dc954da304f05292da9dea

(there's another couple of passing TODOs related to alerts in error log; I'll handle those separately)
