### ISSUE TITLE
Error version 1016000 instead of 1016001

### ISSUE THREAD

**Issue by darkeyesz** [SpiderLabs/ModSecurity-nginx#166]
This morning I restarted nginx and found this error:

[emerg] 3696#3696: module "/etc/nginx/modules/ngx_http_modsecurity_module.so" version 1016000 instead of 1016001 in /etc/nginx/nginx.conf:6

My Nginx version is:
 
nginx version: nginx/1.16.1

Last time I've configured ModSecurity with:

./configure --with-compat --add-dynamic-module=../ModSecurity-nginx

**Comment by victorhora** [comment]
Hi @darkeyesz,

These errors can happen when upgrading the Nginx version without recompiling the module, or the other way around (running a module compiled from a newer version of Nginx). I think Recompiling the module should solve your issue.

**Comment by darkeyesz** [comment]
Thank u for suggestion. I've recompiled with correct version of nginx now installed:

nginx version: nginx/1.16.1

Bye!
