### ISSUE TITLE
ModSecurity-nginx 1.0.1 and auditlog

### ISSUE THREAD

**Issue by cello86** [SpiderLabs/ModSecurity-nginx#176]
Hi All,
we noticed that the modsecurity-nginx-v1.0.1 dosn't generate the audit.log in Serial and Concurrent mode. We can reproduce the issue and if we rollback the connection to version v1.0.0 all works fine.

Is it a know issue?

Thanks,
Marcello

**Comment by victorhora** [comment]
Hi @cello86 yes, it is a known issue and there's a patch available for testing at https://github.com/SpiderLabs/ModSecurity-nginx/pull/175. Please let us know if it solves your issue and report back at issue https://github.com/SpiderLabs/ModSecurity-nginx/issues/170. 

Thanks.
