### ISSUE TITLE
Negation on operators not working

### ISSUE THREAD

**Issue by masterdead** [SpiderLabs/ModSecurity-nginx#18]
Hi,

iam tried to use negation on operator eg. !@ipmatch, but not work.
If i use this rule
`SecRule REMOTE_ADDR "!@ipmatch 172.16.71.132" \
      "msg:'DENY TEST',\
      id:1,\
      t:none,\
      deny"`
but in debug log operator starting without !
`[4] (Rule: 1) Executing operator "@ipmatch" with param "172.16.71.132" against REMOTE_ADDR.`

And question is, negation is not implemented?

**Comment by zimmerle** [comment]
Hi @masterdead,

Sorry for the delay. In fact, the `negation' variation was not enabled to the ipmatch operator. Recent change s on the libModSecurity code (SpiderLabs/ModSecurity@8757840bc3c2231060c2af1853a83d258f0129ed) enables the negation variation to all the operators.
