### ISSUE TITLE
Bruteforce rule gives error "Expecting an action, got:  %{args.log}',expirevar:'ip.multiple_username_count=60"

### ISSUE THREAD

**Issue by rahulbhatu** [SpiderLabs/ModSecurity-nginx#184]
Hello All,

We have below setup
ModSec 3.0.4 + 1.0.1 Modsecurity-nginx

most of the modsecurity Rules work Fine but bruteforce Rule seems to error out.

This is the error 
`File: 09_Bruteforce_Bruteforce.conf. Line: 67. Column: 156. Expecting an action, got:  %{args.log}',expirevar:'ip.multiple_username_count=60'" `

This is the rule which seems to error

```
SecMarker GENERIC_POST_BRUTEFORCE_END
SecRule REQUEST_FILENAME "@contains wp-login.php" \
        "id:230010,chain,phase:2,pass,nolog,t:none,rev:3,severity:2,tag:'WAF',tag:'Bruteforce'"
SecRule REQUEST_METHOD "@streq POST" \
        "chain"
SecRule &ARGS:log "!eq 0" \
        "chain"
SecRule &IP:PREVIOUS_USERNAME "@eq 0" \
        "setvar:'ip.previous_username=%{args.log}'"


SecRule REQUEST_FILENAME "@contains wp-login.php" \
"id:230011,chain,msg:' Multiple Username Violation: Too Many Usernames Submitted for Authentication.||%{tx.domain}|%{tx.mode}|2',phase:2,block,logdata:'Current Username: %{args.log}',t:none,rev:3,severity:2,tag:'WAF',tag:'Bruteforce'"
SecRule REQUEST_METHOD "@streq POST" \
       "chain"
SecRule &ARGS:log "!@eq 0" \
       "chain"
SecRule &IP:PREVIOUS_USERNAME "@eq 1" \
       "chain"
SecRule ARGS:log "!within %{ip.previous_username}" \
       "chain,setvar:'ip.multiple_username_count=+1',setvar:'ip.previous_username=%{ip.previous_username}, %{args.log}',expirevar:'ip.multiple_username_count=60'"
SecRule IP:MULTIPLE_USERNAME_COUNT "@gt 5"
```

**Comment by martinhsv** [comment]
Hi @rahulbhatu ,

It looks like second setvar in the second-last SecRule is not correct.  You have
```
 setvar:'ip.previous_username=%{ip.previous_username}, %{args.log}'
```
The portion after the equals sign has two different variables separated by a comma.  Normally the portion after the '=' is just a single other variable.

Perhaps it's a simple error, such as that you actually intended it to look more the setvar action in the last rule of id:230010?
```
setvar:'ip.previous_username=%{args.log}'
```

**Comment by rahulbhatu** [comment]
Hi @martinhsv 

Thanks for looking into it.
 
I did not change anything form the default rules however even i realized that there should only be one variable in setvar after removing any one of them `nginx -t` works but i am not sure which out of 
```
'ip.previous_username=%{ip.previous_username}, and  %{args.log}'
```
to keep so that rule works fine. i wish to test this rule as well.

**Comment by martinhsv** [comment]
Hi @rahulbhatu ,

The 230010 and 230011 rules that you have cited are not 'default rules' from ModSecurity per se.

As an open source project, other individuals and groups are able to compose and provide rules that work with ModSecurity.  However, neither https://github.com/SpiderLabs/ModSecurity-nginx nor https://github.com/SpiderLabs/ModSecurity are really the right place for issues related to rules composed by such third parties.

If you have downloaded a rule package from some source, any inquiries about those specific rules are best directed to that source.  (For example, a quick internet search suggests that perhaps you got those rules from Comodo?)

Cheers
