### ISSUE TITLE
Docker/Nginx/ModSecurity/DetectionOnly doest not log

### ISSUE THREAD

**Issue by linkos82** [SpiderLabs/ModSecurity-nginx#186]
Hi,

We have configured modsecurity on docker with the image from owasp/modsecurity:latest

When it is configured in DetectionOnly, we have no logs in nginx while when it is in On Mode the homemade rules are blocked and it is logging in nginx.

We do not have specific configurations on the container.

**Comment by martinhsv** [comment]
Hi @linkos82 ,

ModSecurity v3.0.3 had a bug that had an effect like that.  Is it possible that that's the version you're using?  That problem was corrected in v3.0.4.

**Comment by linkos82** [comment]
Hi martinhsv,

Thanks, we now have the warning logs in auditlog with ModSecurity 3.0.4 in DetectionOnly mode. But they are not sent to nginx log just in AuditLog. 
We also can't define SecAuditLogFormat with JSON format, as modsecurity has not been compiled with JSON support, are you going to fix that ?

**Comment by martinhsv** [comment]
Hi @linkos82 ,

Those Docker images are supported by a different group.  If your source is https://hub.docker.com/r/owasp/modsecurity , then you may wish to inquire at the help/issues locations referenced there.

**Comment by linkos82** [comment]
Hi @martinhsv,

I will open an issue there. But can you confirm it is normal in DetectionOnly mode to have only the logs in AuditLog et not in Nginx log ?
Thanks a lot for you reply

**Comment by martinhsv** [comment]
Hi @linkos82 ,

With a typical, default configuration, that would be expected behaviour .

It is possible, however, to change that nginx configuration.

The default setting for error_log (usually in your nginx.conf file) is typically 'warn'.  To get additional output to error.log, you can increase this to 'info' or 'debug'.

Cheers.
