### ISSUE TITLE
client_body_in_file_only getting deleted

### ISSUE THREAD

**Issue by shmurf** [SpiderLabs/ModSecurity-nginx#187]
When setting 
`client_body_in_file_only on;`
nginx is supposed to cache the user request body to a file and NOT delete it, this is convenient for debugging.
However with modsec on I realized that the file gets deleted even when set to ON.

**Comment by martinhsv** [comment]
Hello @shmurf ,

Thank you for raising that.

I can confirm your report ... and I think I see the problem.

**Comment by zimmerle** [comment]
Closed as #194 got merged! I was expecting GitHub to do it automagically :P
