### ISSUE TITLE
Does ModSecurity-nginx now is static build with nginx?

### ISSUE THREAD

**Issue by louishot** [SpiderLabs/ModSecurity-nginx#189]
Does ModSecurity-nginx is static build with nginx? Does it mean that nginx build completed can be remove libmodsecurity?

**Comment by louishot** [comment]
all right I see /usr/local/modsecurity/lib/libmodsecurity.so.
 so libmodsecurity not in nginx binary

**Comment by martinhsv** [comment]
Hi @louishot ,

It sounds like you've answered your own question.  I'll go ahead and close this.
