### ISSUE TITLE
Certbot issue

### ISSUE THREAD

**Issue by ManuChao97** [SpiderLabs/ModSecurity-nginx#197]
Hello,
Sorry for my bad English because i'm french.
So, I am experiencing a malfunction in my NGINX server.
When I try to update my certificates with CERTBOT I get the following error:

```
root@XXX:/# certbot 
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Error while running nginx -c /etc/nginx/nginx.conf -t.

nginx: [emerg] module "/etc/nginx/modules/ngx_http_modsecurity_module.so" version 1017010 instead of 1018000 in /etc/nginx/nginx.conf:1
nginx: configuration file /etc/nginx/nginx.conf test failed


Certbot doesn't know how to automatically configure the web server on this system. However, it can still get a certificate for you. Please run "certbot certonly" to do so. You'll need to manually configure your web server to use the resulting certificate.
```

Thx

`root@XXX:/# nginx -v
nginx version: nginx/1.18.0
`

**Comment by zimmerle** [comment]
Hi @ManuChao97,

It seems like you have compiled ModSecurity for Nginx 1018000, and you are trying to use 1017010. Please compile ModSecurity-nginx for the same Nginx version that you have installed on your system.
