### ISSUE TITLE
Rule ID missing from Modsecurity Audit logs

### ISSUE THREAD

**Issue by rahulbhatu** [SpiderLabs/ModSecurity-nginx#214]
Hello All,

we have a setup of ModSecurity + Modsecurity-Nginx from master. we are using JSON format for modsecurity Auditlog. logs contain messages section that contain information about the rules that triggered it.  
like below example .

`{"message":" Inbound Points Exceeded|Total Incoming Points: 5|example.com|F|2","details":{"match":"Matched \"Operator `Ge' with parameter `5' against variable `TX:INCOMING_POINTS' (Value: `5' )","reference":"","ruleId":"214930","file":"/etc/nginx/modsec/waf/20_Outgoing_FiltersEnd.conf","lineNumber":"32","data":"","severity":"2","ver":"","rev":"1","tags":["WAF","FiltersEnd"],"maturity":"0","accuracy":"0"}}]}}`

But every now and then we are seeing empty messages section in Audit logs this is making it harder to track which rule is blocking the requests. like below example here messages section is empty [].

`{"transaction":{"client_ip":"xx.xx.xx.xx","time_stamp":"Tue Jul  7 14:15:51 2020","server_id":"474b1dfa0a32e45055d8b70069a09292af72bbe6","client_port":0,"host_ip":"xx.xx.xx.xx","host_port":443,"unique_id":"159413135176.639672","request":{"method":"POST","http_version":1.1,"uri":"/xmlrpc.php","headers":{"User-Agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0","X-Forwarded-Proto":"https","CF-Visitor":"{\"scheme\":\"https\"}","Content-Length":"475","X-Forwarded-For":"xx.xx.xx.xx","CF-IPCountry":"DE","Host":"example.com","Accept-Encoding":"gzip","Connection":"Keep-Alive","CDN-Loop":"cloudflare","CF-RAY":"5af22e0fea0fbf69-SIN","Content-Type":"application/x-www-form-urlencoded","CF-Request-ID":"03cb3b1df20000bf69d5851200000001","CF-Connecting-IP":"xx.xx.xx.xx"}},"response":{"http_code":403},"producer":{"modsecurity":"ModSecurity v3.0.4 (Linux)","connector":"ModSecurity-nginx v1.0.1","secrules_engine":"Enabled","components":["WAF_Apache\""]},"messages":[]}}`

Also SecDefaultAction is set to have auditlog
```
SecDefaultAction \
        "phase:1,deny,log,auditlog"

SecDefaultAction \
        "phase:2,deny,status:403,log,auditlog"
```

Also any rule does not conatin "noauditlog" in the rules action part. can someone point why rule id are missing from logs or what can be missing 

Thanks

**Comment by zimmerle** [comment]
Hi @rahulbhatu,

Thanks for the report. It could be a regression on [libModSec v3/master](https://github.com/SpiderLabs/ModSecurity). As a workaround can you use [v3.0.4](https://github.com/SpiderLabs/ModSecurity/releases/tag/v3.0.4)?

Formatted JSON for easy readability -

```json
{
   "message":" Inbound Points Exceeded|Total Incoming Points: 5|example.com|F|2",
   "details":{
      "match":"Matched \"Operator Ge' with parameter 5' against variable TX:INCOMING_POINTS' (Value: 5' )",
      "reference":"",
      "ruleId":"214930",
      "file":"/etc/nginx/modsec/waf/20_Outgoing_FiltersEnd.conf",
      "lineNumber":"32",
      "data":"",
      "severity":"2",
      "ver":"",
      "rev":"1",
      "tags":[
         "WAF",
         "FiltersEnd"
      ],
      "maturity":"0",
      "accuracy":"0"
   }
}
```

```json
{
   "transaction":{
      "client_ip":"xx.xx.xx.xx",
      "time_stamp":"Tue Jul 7 14:15:51 2020",
      "server_id":"474b1dfa0a32e45055d8b70069a09292af72bbe6",
      "client_port":0,
      "host_ip":"xx.xx.xx.xx",
      "host_port":443,
      "unique_id":"159413135176.639672",
      "request":{
         "method":"POST",
         "http_version":1.1,
         "uri":"/xmlrpc.php",
         "headers":{
            "User-Agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0",
            "X-Forwarded-Proto":"https",
            "CF-Visitor":"{\"scheme\":\"https\"}",
            "Content-Length":"475",
            "X-Forwarded-For":"xx.xx.xx.xx",
            "CF-IPCountry":"DE",
            "Host":"example.com",
            "Accept-Encoding":"gzip",
            "Connection":"Keep-Alive",
            "CDN-Loop":"cloudflare",
            "CF-RAY":"5af22e0fea0fbf69-SIN",
            "Content-Type":"application/x-www-form-urlencoded",
            "CF-Request-ID":"03cb3b1df20000bf69d5851200000001",
            "CF-Connecting-IP":"xx.xx.xx.xx"
         }
      },
      "response":{
         "http_code":403
      },
      "producer":{
         "modsecurity":"ModSecurity v3.0.4 (Linux)",
         "connector":"ModSecurity-nginx v1.0.1",
         "secrules_engine":"Enabled",
         "components":[
            "WAF_Apache\""
         ]
      },
      "messages":[

      ]
   }
}
```

**Comment by rahulbhatu** [comment]
Hi @zimmerle 

sorry for the confusion we are already using ModSecurity v3.0.4 and Modsecurity-Nginx v1.0.1.

**Comment by rahulbhatu** [comment]
Hi @zimmerle 

Anything else I can check for the missing rule ID in the audit logs. I tried some tests but no luck yet.

Thanks
Rahul

**Comment by rahulbhatu** [comment]
Update --

I came across this thread[https://github.com/SpiderLabs/ModSecurity/issues/1866](url) and based on @kanitan's comment i checked my modsecurity config file i had this in my config. 

`SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "403"`

After commenting #SecAuditLogRelevantStatus "403" in config file all the audit logs entries now contains Rule IDs 
 
so now the problem is, if SecAuditLogRelevantStatus "403" was meant to record all the actions that produced 403 statuscode even if its not blocked by modsecurity and some other ways then i am performing some actions that gives me 403 statuscode but are not recorded in audit logs.

**Comment by zimmerle** [comment]
wat?????????????????
