### ISSUE TITLE
Nginx is not clearing body cache

### ISSUE THREAD

**Issue by krewi1** [SpiderLabs/ModSecurity-nginx#216]
Hello, we have found a possible regression on master branch. When request body exceeds buffer body size it is stored on disk and never cleared up, which results into possible storage problems.
Here is [repo](https://github.com/krewi1/nginxmodsec) with minimal setup. Nginx is configured to store data in /tmp folrder. There is for sure possibility that error is in configuration. But we didn't found it. We have fallbacked to version v1.0.1. Fallback is tested in branch fix.

**Comment by martinhsv** [comment]
Hi @krewi1 ,

Thanks for the report.

As you suggest, I cannot rule out a configuration issue, but, like you, I don't immediately see a problem there either.

On the other hand, the post-v1.0.1 commit https://github.com/SpiderLabs/ModSecurity-nginx/commit/83682d294e21edc8039f35257dffecc71f2432b0 may have caused an unintended side-effect like what you describe.

If you're interested, you could consider confirming that commit is indeed the cause of the difference in behaviour (i.e. try using both versions of the code both pre- and post- that commit).

**Comment by krewi1** [comment]
Well yeah i have just tested it and it seems that that  commit is problematic.
