### ISSUE TITLE
Error in nginx -t  (not binary compatible)

### ISSUE THREAD

**Issue by noideaplshelp** [SpiderLabs/ModSecurity-nginx#221]
i need help with this, seems like after one problem, i came up with a solution, there's always one more. here is the error:;

[root@centos7 nginx]# nginx -t
nginx: [emerg] module "/usr/share/nginx/ngx_http_modsecurity_module.so" is not binary compatible in /etc/nginx/nginx.conf:10
nginx: configuration file /etc/nginx/nginx.conf test failed

here is my nginx.conf:

# For more information on configuration, see:
#   * Official English Documentation: http://nginx.org/en/docs/
#   * Official Russian Documentation: http://nginx.org/ru/docs/

user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

load_module ngx_http_modsecurity_module.so;

# Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;

anytype of contribution is much appreciated  D:

**Comment by martinhsv** [comment]
Hi @noideaplshelp ,

I think the only time I have encountered that error is if I forget to include '--with-compat' when doing the configure for the build of the dynamic module.

That would be in step 4.4 if you happening to be using these instructions:  https://www.nginx.com/blog/compiling-and-installing-modsecurity-for-open-source-nginx/

If that's not it, I'd probably take a moment to review the other steps and make sure I didn't miss anything.
