### ISSUE TITLE
nginx[17258]: nginx: [emerg] dlopen() "/etc/nginx/nginx/modules/ngx_http_modsecurity_module.so" failed (/etc/nginx/nginx/modules/ngx_http_modsecurity_module.so: cannot open shared object file: No such file or directory) in /etc/nginx/nginx.conf:5

### ISSUE THREAD

**Issue by satchidipu174** [SpiderLabs/ModSecurity-nginx#223]
Please look into the issue

**Comment by martinhsv** [comment]
Hi @satchidipu174 ,

It is likely that either either A) you didn't build the ModSecurity nginx connector or B) you didn't copy the .so file to the correct location.

For example, if you were following the instructions at this site:   https://www.linuxjournal.com/content/modsecurity-and-nginx

... make sure that when you do the step at "Now you need to copy the connector module ... ", that you copy the .so file to the same file location that you specified with load_module directive in your nginx conf file.
