### ISSUE TITLE
SecAuditLogType Concurrent does not write to SecAuditLog file when DetectionOnly

### ISSUE THREAD

**Issue by kwaazaar** [SpiderLabs/ModSecurity-nginx#226]
When switched on, requests are blocked and audit-log (main/index file) contains entries. But for safety we first want to use DetectionOnly to find out which/how many requests would be blocked. This is only possible to find out by investigating all individual files in the subfolders (concurrent logging). This is undoable for a production environment.

Is this by design? If so, can you provide guidance on what other way of working I could use?

**Comment by martinhsv** [comment]
Hi @kwaazaar ,

I'm not entirely sure I understand what you're asking.

The title of your posting ('DetectionOnly does not write to audit-log') would seem to contradict what you have written in your description -- where it sounds like the audit log *is* being written to, but that you find the multiple-file format of the Concurrent logging setting to be inconvenient.  (Just guessing, but perhaps you meant nginx's error.log in the title?)

As to the multiple-file format of Concurrent logging:  not writing everything to the same file is definitely part of the point as it scales better.

If you don't feel that you need Concurrent logging at this time, one option is to change to Serial -- at least for your initial experimental period.

Other approaches might involve at least some minor post-processing to make things more convenient.

You could 'cat' a set of one day's files to make examination more convenient.  You could alternatively process this output to only extract the key data ( e.g. if using native log format:  'cat */* | grep "id:" ' ).

I hope that helps.

**Comment by kwaazaar** [comment]
When I have SecRuleEngine On and I perform a call with a SQL-injection attempt, I get:
- One entry in modsec_audit.log
~~~
tokenservice.dev.aahg.ot 10.244.52.39 - [07/Oct/2020:16:59:30 +0000] "GET /js/app.js?v=Gsu4sFItaTwp3aOUy_09-WEhBjVNZu-Qh7WaP6AGtwI HTTP/1.1" 200 0 https://tokenservice.dev.aahg.ot/Login?ReturnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3DSitecore%26redirect_uri%3Dhttps%253A%252F%252Fontwikkel-florius-sc9.aahg.ot%252Fidentity%252Fexternallogincallback%26response_mode%3Dform_post%26response_type%3Dcode%2520id_token%26scope%3Dopenid%2520offline_access%2520account%2520klant%2520lening%26state%3DOpenIdConnect.AuthenticationProperties%253DZ54bHIzYnLyplYRBgrCxdfGfCk6V0nUqjzl4RxWv44adJ8bK2R9DSc3K15rHnqBcOLcBEF_xQnPrHly0TG54N3C__8oHjR9I5l82Hv96OQDkwlbDbwuQrOplTWgCUrheTGYW3P06d6aRuPd01-Ccayh6MCIH_4nd0KEDdFCvsyD1lvSmU0GlaRxg0rBRj_4j28GoJ8mDua6_0FsKKZkpgC06UOyZrJ6BCTPgmwA0jkEZmsE9Le-zitZmX_b-s4oxO5ND9JJZWfE19MnsumEfcNRzqlobSgQPHk_dPW1n8oXcJU701PXtQCvxfZ77rhwwQUU7oJ7q3q1WyYtFoJeIbhgxEVVSdWO5q_2dwEaCNy2sdR2Hbe64w-TgT00a39tDZjHypZIcSk7GneucgNo6JA%26nonce%3D637376765256186571.MzE5YTBmZjEtZTQ0NS00NTgzLWFiYzItN2RjYzZjMjAzY2M0OTMwZTNhYzgtYWEyYS00Yzc1LWIyYzUtZjU4ODI1ZWRlZTFl%26x-client-SKU%3DID_NET%26x-client-ver%3D1.0.40306.1554&x=%27%20or%201=1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36" 160208997039.956762 https://tokenservice.dev.aahg.ot/Login?ReturnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3DSitecore%26redirect_uri%3Dhttps%253A%252F%252Fontwikkel-florius-sc9.aahg.ot%252Fidentity%252Fexternallogincallback%26response_mode%3Dform_post%26response_type%3Dcode%2520id_token%26scope%3Dopenid%2520offline_access%2520account%2520klant%2520lening%26state%3DOpenIdConnect.AuthenticationProperties%253DZ54bHIzYnLyplYRBgrCxdfGfCk6V0nUqjzl4RxWv44adJ8bK2R9DSc3K15rHnqBcOLcBEF_xQnPrHly0TG54N3C__8oHjR9I5l82Hv96OQDkwlbDbwuQrOplTWgCUrheTGYW3P06d6aRuPd01-Ccayh6MCIH_4nd0KEDdFCvsyD1lvSmU0GlaRxg0rBRj_4j28GoJ8mDua6_0FsKKZkpgC06UOyZrJ6BCTPgmwA0jkEZmsE9Le-zitZmX_b-s4oxO5ND9JJZWfE19MnsumEfcNRzqlobSgQPHk_dPW1n8oXcJU701PXtQCvxfZ77rhwwQUU7oJ7q3q1WyYtFoJeIbhgxEVVSdWO5q_2dwEaCNy2sdR2Hbe64w-TgT00a39tDZjHypZIcSk7GneucgNo6JA%26nonce%3D637376765256186571.MzE5YTBmZjEtZTQ0NS00NTgzLWFiYzItN2RjYzZjMjAzY2M0OTMwZTNhYzgtYWEyYS00Yzc1LWIyYzUtZjU4ODI1ZWRlZTFl%26x-client-SKU%3DID_NET%26x-client-ver%3D1.0.40306.1554&x=%27%20or%201=1 /var/modsec/audit//20201007/20201007-1659/20201007-165930-160208997039.956762 0 5053.000000 md5:17d43e3e7714cfb250e458facf3688ed
~~~
- One file on disk with more details about the request named /var/modsec/audit//20201007/20201007-1659/20201007-165930-160208997039.956762
- The call is blocked and HTTP 403 is returned.

When I set SecRuleEngine to DetectionOnly, I would expect the same result, except the call is not blocked. What I see is that there are also no entries written to modsec_audit.log.

**Comment by martinhsv** [comment]
Hi @kwaazaar ,

Thank you for the clarification.  I see what you mean.

It is possible that the behaviour you describe is by design.

However, given the nature of the entries written to the SecAuditLog file when using 'SecAuditLogType Concurrent' (i.e. that the SecAuditLog lines are an index listing of the files created within the SecAuditLogStorageDir directory), I cannot think of a good reason for the entries to be absent when DetectionOnly.

I will tentatively call this a bug and will follow up on this.

**Comment by martinhsv** [comment]
I was initially able to reproduce the reported behaviour in v3.0.4 ( at least I _thought_ I was able to do so).

But now I cannot.  With Concurrent+DetectionOnly, the index entries appear in the SecAuditLog file, just the same as with SecRuleEngine On.

For reference, what version of ModSecurity are you running?

**Comment by kwaazaar** [comment]
I'm not sure which version I'm using. I use the nginx-ingress helm chart.

NGINX Ingress controller
  Release:       0.33.0
  Build:         git-589187c35
  Repository:    https://github.com/kubernetes/ingress-nginx
  nginx version: nginx/1.19.0

I don't know which version of ModSecurity is shipped.

**Comment by martinhsv** [comment]
I have not been able to reproduce this since the original activity regarding this report. I'm going to go ahead and close this item for that reason.

If this is encountered as an issue in the future, a new issue can be opened -- hopefully with enough detail to allow it to be reproduced.
