### ISSUE TITLE
hmac settings failed 

### ISSUE THREAD

**Issue by pengyejun** [SpiderLabs/ModSecurity-nginx#229]
reference the link https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/modsecurity-advanced-topic-of-the-week-hmac-token-protection/
I try to configure hmac in modsecurity, but the homepage is loaded disorderly。

hmac_debug file

![hmac](https://user-images.githubusercontent.com/31479786/98913444-54ee5580-2502-11eb-9414-19c00548ded4.png)
hmac config file

![hmac_config](https://user-images.githubusercontent.com/31479786/98913454-5881dc80-2502-11eb-970b-5755b0e1b2ed.png)

old page
<img width="1773" alt="old_page" src="https://user-images.githubusercontent.com/31479786/98913620-8cf59880-2502-11eb-9bc4-27f27d522025.png">

destory page
<img width="1437" alt="destroy" src="https://user-images.githubusercontent.com/31479786/98913649-9a128780-2502-11eb-8cd5-f3299cb2190d.png">

system version MacOS10.15
modsecurity version:2.9.2
nginx version:1.11.12

And I found the same problem on ubuntu(4.8.2-19)

**Comment by martinhsv** [comment]
Closing as a duplicate of:  https://github.com/SpiderLabs/ModSecurity/issues/2450
