### ISSUE TITLE
How does this module differ from nginx-plus-module-modsecurity?

### ISSUE THREAD

**Issue by byy247** [SpiderLabs/ModSecurity-nginx#247]
@zimmerle

**Comment by zimmerle** [comment]
@byy247 I think the best person to details the differences for you is @defanator.

**Comment by defanator** [comment]
@byy247 the nginx-plus-module-modsecurity includes both this connector module and the libmodsecurity from https://github.com/spiderlabs/modsecurity in a precompiled (binary) form. There are no any customizations. Moreover, you can build a similar binary package for nginx/foss as well, see http://hg.nginx.org/pkg-oss/ for details.
