### ISSUE TITLE
error compiling with nginx 1.21.5

### ISSUE THREAD

**Issue by arielesp** [SpiderLabs/ModSecurity-nginx#262]
make[1]: *** [objs/Makefile:2101: objs/addon/src/ngx_http_modsecurity_module.o] Error 1
make[1]: Leaving directory '/opt/nginx-1.21.5'
make: *** [Makefile:10: build] Error 2
make -f objs/Makefile install
make[1]: Entering directory '/opt/nginx-1.21.5'
cc -c -fPIC -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -O2 -flto -funsafe-math-optimizations -Wformat -Werror=format-security  -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=native -fPIC -DTCP_FASTOPEN=23 -Wno-deprecated-declarations -I/opt/nginx-rtmp-module -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/local/modsecurity/include -I /opt/openssl-1.1.1m/.openssl/include -I objs -I src/http -I src/http/modules -I src/http/v2 -I /opt/ngx_brotli/deps/brotli/c/include -I /opt/nginx-rtmp-module \
        -o objs/addon/src/ngx_http_modsecurity_module.o \
        /opt/ModSecurity-nginx/src/ngx_http_modsecurity_module.c
/opt/ModSecurity-nginx/src/ngx_http_modsecurity_module.c: In function ‘ngx_http_modsecurity_pcre_malloc_init’:
/opt/ModSecurity-nginx/src/ngx_http_modsecurity_module.c:78:9: error: ‘pcre_malloc’ undeclared (first use in this function); did you mean ‘old_pcre_malloc’?
     if (pcre_malloc != ngx_http_modsec_pcre_malloc) {
         ^~~~~~~~~~~
         old_pcre_malloc
/opt/ModSecurity-nginx/src/ngx_http_modsecurity_module.c:78:9: note: each undeclared identifier is reported only once for each function it appears in
/opt/ModSecurity-nginx/src/ngx_http_modsecurity_module.c:82:25: error: ‘pcre_free’ undeclared (first use in this function); did you mean ‘pkey_free’?
         old_pcre_free = pcre_free;
                         ^~~~~~~~~
                         pkey_free
/opt/ModSecurity-nginx/src/ngx_http_modsecurity_module.c: In function ‘ngx_http_modsecurity_pcre_malloc_done’:
/opt/ModSecurity-nginx/src/ngx_http_modsecurity_module.c:102:9: error: ‘pcre_malloc’ undeclared (first use in this function); did you mean ‘old_pcre_malloc’?
         pcre_malloc = old_pcre_malloc;
         ^~~~~~~~~~~
         old_pcre_malloc
/opt/ModSecurity-nginx/src/ngx_http_modsecurity_module.c:103:9: error: ‘pcre_free’ undeclared (first use in this function); did you mean ‘pkey_free’?
         pcre_free = old_pcre_free;
         ^~~~~~~~~
         pkey_free
make[1]: *** [objs/Makefile:2101: objs/addon/src/ngx_http_modsecurity_module.o] Error 1
make[1]: Leaving directory '/opt/nginx-1.21.5'
make: *** [Makefile:13: install] Error 2

using 1.21.4 works fine

**Comment by defanator** [comment]
See #260 and #261.

**Comment by njabulomatabane80-crypto** [comment]
Heuhe
