### ISSUE TITLE
‘pcre_malloc’ undeclared on make modules

### ISSUE THREAD

**Issue by navotera** [SpiderLabs/ModSecurity-nginx#264]
Hello I try to install the latest version of this repo by cloning the repo with git clone and with nginx 1.21.5 when I try to run 'make modules' command, I got this error : 
 
 error: ‘pcre_malloc’ undeclared (first use in this function); did you mean ‘old_pcre_malloc’?
   78 |     if (pcre_malloc != ngx_http_modsec_pcre_malloc) {
      |         ^~~~~~~~~~~
      
  Please give some suggestions
  Thank

**Comment by defanator** [comment]
@navotera please check #260 (long story short - use `--without-pcre2` configure argument when building connector with nginx >= 1.21.5).

**Comment by navotera** [comment]
Thank you for your suggestion. 
It thankfully works without any problem 👍
