### ISSUE TITLE
Is there a way to check how much time to go over all rules in modsecurity

### ISSUE THREAD

**Issue by jingzhao-self** [SpiderLabs/ModSecurity-nginx#288]
Hi team,
Right now I have some performance issues after modsecurity is on, and don't know how to get process time of modsecurity rules on each http request, is there a way to show it? 
I have checked $request_time in nginx log but it seems not include modsecurity process time.
Thanks

**Comment by airween** [comment]
May be it can help (and may be cannot), there is a tool: [ftwrunner](https://github.com/digitalwave/ftwrunner) (there is a beta version of new [release](https://github.com/digitalwave/ftwrunner/tree/v1.0/dev)).

It uses the test case format of [CRS](https://github.com/coreruleset/coreruleset/tree/v4.0/dev/tests/regression/tests). With this, you can make a request in that format, and can measure the runtime. Also you can remove rules, if you are sure those aren't effected.

**Comment by martinhsv** [comment]
Hello @jingzhao-self ,

WIth ModSecurity v3, there are a few options, one of the simplest is using the DURATION variable. Outputting that value at selected points in your rule set can help narrow down where your most substantial performance issues are.

Another tool (besides the one already mentioned above) that you could consider experimenting with is referenced here: https://github.com/SpiderLabs/ModSecurity/issues/1011#issuecomment-337212177
