### ISSUE TITLE
Error occur randomly on images

### ISSUE THREAD

**Issue by TrungACZNE** [SpiderLabs/ModSecurity-nginx#3]
`net::ERR_INCOMPLETE_CHUNKED_ENCODING` and `net::ERR_CONTENT_LENGTH_MISMATCH` occur randomly on images served via proxy_pass to a static site. Didn't even activate modsecurity in config.

Build:
```
(commit hashes are all their branches' HEAD atm, listing them down just in case)
Ubuntu 14.04
nginx-1.9.5
libinject - copied from Modsecurity's fecefbe8b4fc628dfef9ebff0317bfb9fd871078 (apache2/libinject directory)
libmodsecurity - 283c8c818db1e11fb496064b6cc1158ebe947d58
ModSecurity-nginx - 1713be9e7ca5c95d5c09df59e3c62e548072af0d
```
nginx.conf
```
user www-data;
worker_processes 2;
pid /run/nginx.pid;

events {
        worker_connections 2048 ;
        # multi_accept on;
}

http {
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;

        include mime.types;
        default_type application/octet-stream;
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        gzip on;
        gzip_disable "msie6";

        server {
                listen       80;
                server_name  <my server name>;
                location / {
                        proxy_pass http://<my ip>;
                }
        }
}
```

It happens at random intervals - reloading may make the image load again. Also when encountering the wrong CONTENT_LENGTH_MISMATCH error, Content-Length header was correct, so it's probably the image's body returned that's wrong.

**Comment by zimmerle** [comment]
Hi @TrungACZNE,

I was trying to reproduce the problem here without success. 

Here is what I was using:
```
libmodsecurity: 47a62b98bbc486fadb28e62db910195577aea228
nginx: 1.9.12
nginx connector: 221a134181cf316033e36d7573a4c79689f2a835
```


Do you mind to test it again? with fresh versions?

**Comment by TrungACZNE** [comment]
Hi,

I forgot to close this after awhile. It's a misconfiguration on my side. I don't have exactly the details about my old configuration though, it's been a long time since.

Sorry for wasting your time.

**Comment by zimmerle** [comment]
No problem.

Thanks @TrungACZNE
