### ISSUE TITLE
Which branch to use? 

### ISSUE THREAD

**Issue by mimugmail** [SpiderLabs/ModSecurity-nginx#30]
Hi, 

I'm not sure which branch to use right now? My last info was the experimental branch but it seems outdated againt master. Shall we switch to master? I've several segfaults with N+ and searching for a solution (also on modsec_dev list)

Thanks!

**Comment by zimmerle** [comment]
Hi @mimugmail,

Please keep using the master branch, as you highlighted the experimental is currently out-of-date. Are you referring a segfault during the restart? If not, please try to recompile with: --without-lmdb
