### ISSUE TITLE
macos 环境下编译错误

### ISSUE THREAD

**Issue by FarmerLi** [SpiderLabs/ModSecurity-nginx#313]
config 文件中
`ngx_feature_name=`
`ngx_feature_run=no`
`ngx_feature_incs="#include <modsecurity/modsecurity.h>"`
`ngx_feature_libs="-lmodsecurity"`
`ngx_feature_test='printf("hello");'`
`ngx_modsecurity_opt_I=`
`ngx_modsecurity_opt_L=`
ngx_feature_test 使用了printf，但是没有 #include <stdio.h> ，导致编译检查组件时无法通过测试，建议调整为：
`ngx_feature_incs="#include <stdio.h>\n#include <modsecurity/modsecurity.h>"`

**Comment by martinhsv** [comment]
It's unclear what this is about. Closing.

(Please keep in mind, that this repo is being operated in English, as the best choice for maximum comprehension by the community.)
