### ISSUE TITLE
Website Firewall Not Found on Sucuri SiteCheck test

### ISSUE THREAD

**Issue by kysil** [SpiderLabs/ModSecurity-nginx#33]
Hello,
I have used Compilation recipes at https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes

but still I can see **Website Firewall Not Found**

<img width="838" alt="sucuri" src="https://cloud.githubusercontent.com/assets/5732846/22753047/62fed1f8-ee43-11e6-9e14-525ae4616907.png">

My actions step by step on CentOS 7

NGINX

yum install gcc-c++ flex bison yajl yajl-devel curl-devel curl GeoIP-devel doxygen zlib-devel libtool lmdb-devel -y

yum install ftp://195.220.108.108/linux/fedora/linux/updates/23/x86_64/b/bison-3.0.4-3.fc23.x86_64.rpm -y

cd /usr/local/src/
wget http://nginx.org/download/nginx-1.11.9.tar.gz
tar zxvf nginx-1.11.9.tar.gz
mv /usr/local/src/nginx-1.11.9 /usr/local/src/nginx

wget https://www.openssl.org/source/openssl-1.0.2k.tar.gz
tar -zxf openssl-1.0.2k.tar.gz
mv /usr/local/src/openssl-1.0.2k /usr/local/src/nginx_modules/openssl

curl -L -O http://labs.frickle.com/files/ngx_cache_purge-2.3.tar.gz
tar zxvf ./ngx_cache_purge-2.3.tar.gz
mv /usr/local/src/ngx_cache_purge-2.3 /usr/local/src/nginx_modules/ngx_cache_purge

curl -L -O http://hg.nginx.org/njs/archive/tip.tar.gz
tar zxvf ./tip.tar.gz
mv /usr/local/src/njs-214afa2466a0 /usr/local/src/nginx_modules/njs

git clone https://github.com/google/ngx_brotli.git
mv /usr/local/src/ngx_brotli /usr/local/src/nginx_modules/ngx_brotli
cd /usr/local/src/nginx_modules/ngx_brotli && git submodule update --init && cd /usr/local/src/nginx

bash <(curl -f -L -sS https://ngxpagespeed.com/install) \

mv /userme/ngx_pagespeed-latest-stable /usr/local/src/nginx_modules/ngx_pagespeed

================= libModSecurity ===============

cd /usr/local/src/nginx_modules/
git clone https://github.com/SpiderLabs/ModSecurity

cd /usr/local/src/nginx_modules/ModSecurity
git checkout -b v3/master origin/v3/master
sh build.sh
git submodule init
git submodule update

./configure

make
make install

================= nginx connector =================

export MODSECURITY_INC="/usr/local/src/nginx_modules/ModSecurity/headers/"
export MODSECURITY_LIB="/usr/local/src/nginx_modules/ModSecurity/src/.libs/"

cd /usr/local/src/
git clone https://github.com/SpiderLabs/ModSecurity-nginx
mv /usr/local/src/ModSecurity-nginx /usr/local/src/nginx_modules/ModSecurity-nginx

cd /usr/local/src/nginx_modules/ModSecurity-nginx
git checkout -b experimental origin/experimental

================= nginx ==========================

cd /usr/local/src/nginx
/bin/cp -f /usr/sbin/nginx /usr/sbin/nginx_original_bkp

./configure --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' --with-http_xslt_module=dynamic --with-http_image_filter_module=dynamic --with-http_geoip_module=dynamic --with-http_perl_module=dynamic --add-dynamic-module=/usr/local/src/nginx_modules/njs/nginx --with-openssl=/usr/local/src/nginx_modules/openssl --add-module=/usr/local/src/nginx_modules/ngx_cache_purge --add-module=/usr/local/src/nginx_modules/ngx_brotli --add-module=/usr/local/src/nginx_modules/ngx_pagespeed --add-module=/usr/local/src/nginx_modules/ModSecurity-nginx

make
make install

================= nginx_host.conf =======================

And use this directive rules

…
```
	modsecurity on;
	location /	{
	modsecurity_rules '
	SecRuleEngine On
	SecDebugLog /tmp/modsec_debug.log
	SecDebugLogLevel 9
	SecRule ARGS "@contains test" "id:1,phase:2,t:trim,block"
  ';
	
	try_files	$uri	$uri/	/index.php?$args;
				}
```
…

**Comment by csanders-git** [comment]
@kysil it is unclear how they test this but you don't have any rules beyond just the test rule deployed. You might consider deploying the OWASP Core Rule Set v3.0 and trying again :)
