### ISSUE TITLE
Nginx does not handle the global rules.

### ISSUE THREAD

**Issue by zimmerle** [SpiderLabs/ModSecurity-nginx#34]
Nginx does not handle the global rules.

> http {
> modsecurity on;
> modsecurity_rules_file /etc/nginx/nginx-modsecurity.conf;

If you register for a particular domain in the section server - it works.
What you need to do to work the global rules?

PS: ModSecurity-nginx

This was originally reported by @yvgorshkov at: SpiderLabs/ModSecurity#1328.

**Comment by zimmerle** [comment]
Please check the **new-config-schema** branch here - 
https://github.com/SpiderLabs/ModSecurity-nginx/tree/new-config-schema

We are currently proceeding with tests before merge it into mainline.

**Comment by defanator** [comment]
(Tagging @yvgorshkov here as well.)

**Comment by zimmerle** [comment]
Merged. Global configuration are now available.
