### ISSUE TITLE
nginx is compiled and installed using make error

### ISSUE THREAD

**Issue by maxwalk** [SpiderLabs/ModSecurity-nginx#37]
![image](https://cloud.githubusercontent.com/assets/12889460/23648210/9f4ba322-0354-11e7-8290-6da51d7f709a.png)

How should I fix it?

**Comment by maxwalk** [comment]
Centos 7 Minimal + Nginx-1.8.1
I have used Compilation recipes at https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes

**Comment by defanator** [comment]
Hi @maxwalk,

please try the [v3/dev/parser](https://github.com/spiderlabs/modsecurity-nginx/tree/v3/dev/parser) branch.

Also, nginx/1.8.1 is more than 1 year old, I'd encourage you to use most recent mainline version for testing (1.11.10 at the moment).

**Comment by zimmerle** [comment]
Just a quick notice: As of now the v3/dev/parser on ModSecurity was merged into v3/master. Same for the ModSecurity-nginx.
