### ISSUE TITLE
How to include all CRS rules?

### ISSUE THREAD

**Issue by bali2016** [SpiderLabs/ModSecurity-nginx#39]
I have successfully built a nginx+libmodescuryt+ModSecurity-nginx WAF, and it works when I manully injected a rule in a / url. But when I try to include owasp-crs, seems it can not work. And below are my configures:

nginx.conf
```
server {
        ...
        location / {
            modsecurity on;
            modsecurity_rules_file /usr/local/nginx/conf/modsecurity.conf;
            root   html;
            index  index.html index.htm;
        }
}
```

modsecurity.conf

```
SecRuleEngine On
....
SecStatusEngine On

Include crs-setup.conf
Include rules/*.conf
```

After I reload the nginx,  it can not block malicious attack which can be blocked by the nginx+2.9modscurity. 

So can someone tell me how to configure?

**Comment by met3or** [comment]
Hello @bali2016, hope I can help.  I am using a similar setup and have a single includes file, say for example:

/etc/nginx/modsec_includes.conf 

This will contain -all- of my modsecurity related configuration, and within my nginx virtual host, I will apply it like:

server {
        ...
        location / {
            modsecurity on;
            modsecurity_rules_file /usr/local/nginx/modsec_includes.conf;
            root   html;
            index  index.html index.htm;
        }
}

This include file will have include statements for modsecurity.conf, crs-setup.conf and all of the rules files within the owasp-crs folder,

This setup works quite well for me.

Hope that helps,

Regards,

met3or

**Comment by victorhora** [comment]
Yes, this is a known "limitation" with nginx. "Include rules/*.conf" doesn't work. You need to manually specify each configuration file to be loaded as per:

https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0/master/INSTALL#L132

**Comment by csanders-git** [comment]
A more correct answer is that Nginx with modsecurity v2.x does not use the kleene operator '*' in the same way Apache does. This means that CRS will be loaded out of order. However, the ModSecurity-Nginx connection (libmodsecurity) fixes this issue. Let me know if that solves the issue. If you have other CRS issues feel free to ask on the CRS github  https://github.com/SpiderLabs/owasp-modsecurity-crs

**Comment by bali2016** [comment]
@csanders-git @victorhora @met3or thanks all your help,  now I include all the rules' conf in a file, don't use *.conf, and can see the mailicous attack is blocked.

**Comment by defanator** [comment]
Just to confirm the above explanation from @csanders-git - we were facing exactly the same issue with loading CRS files with `*` mask on earlier versions of libmodsecurity; now it works like a charm.

I did a quick search in `git log`, but was unable to determine the exact changeset, probably @zimmerle has better insights here. :)

**Comment by zimmerle** [comment]
Hi @defanator,

Hard to tell the exactly commit. Most likely it was fixed by one of the parser refactoring commits, where I was working more on a macro view. Collateral benefit ? :)
