### ISSUE TITLE
nginx test cases failed 

### ISSUE THREAD

**Issue by mangeshPSL** [SpiderLabs/ModSecurity-nginx#4]
Hello,
I have to installed nginx through source code.
hg clone http://hg.ginx.org/nginx
then ls
auto  conf  contrib  docs misc  src
there was no configure file to ran ./configure command
I had ran it through auto folder which contains configure .
then make 
make install
output of ./configure  
checking for OS
 + Linux 3.16.0-23-generic x86_64
checking for C compiler ... found
 + using GNU C compiler
 + gcc version: 4.9.1 (Ubuntu 4.9.1-16ubuntu6)
checking for gcc -pipe switch ... found
checking for gcc builtin atomic operations ... found
checking for C99 variadic macros ... found
checking for gcc variadic macros ... found
checking for unistd.h ... found
checking for inttypes.h ... found
checking for limits.h ... found
checking for sys/filio.h ... not found
checking for sys/param.h ... found
checking for sys/mount.h ... found
checking for sys/statvfs.h ... found
checking for crypt.h ... found
checking for Linux specific features
checking for epoll ... found
checking for EPOLLRDHUP ... found
checking for O_PATH ... found
checking for sendfile() ... found
checking for sendfile64() ... found
checking for sys/prctl.h ... found
checking for prctl(PR_SET_DUMPABLE) ... found
checking for sched_setaffinity() ... found
checking for crypt_r() ... found
checking for sys/vfs.h ... found
checking for nobody group ... not found
checking for nogroup group ... found
checking for poll() ... found
checking for /dev/poll ... not found
checking for kqueue ... not found
checking for crypt() ... not found
checking for crypt() in libcrypt ... found
checking for F_READAHEAD ... not found
checking for posix_fadvise() ... found
checking for O_DIRECT ... found
checking for F_NOCACHE ... not found
checking for directio() ... not found
checking for statfs() ... found
checking for statvfs() ... found
checking for dlopen() ... not found
checking for dlopen() in libdl ... found
checking for sched_yield() ... found
checking for SO_SETFIB ... not found
checking for SO_REUSEPORT ... found
checking for SO_ACCEPTFILTER ... not found
checking for TCP_DEFER_ACCEPT ... found
checking for TCP_KEEPIDLE ... found
checking for TCP_FASTOPEN ... found
checking for TCP_INFO ... found
checking for accept4() ... found
checking for eventfd() ... found
checking for int size ... 4 bytes
checking for long size ... 8 bytes
checking for long long size ... 8 bytes
checking for void * size ... 8 bytes
checking for uint64_t ... found
checking for sig_atomic_t ... found
checking for sig_atomic_t size ... 4 bytes
checking for socklen_t ... found
checking for in_addr_t ... found
checking for in_port_t ... found
checking for rlim_t ... found
checking for uintptr_t ... uintptr_t found
checking for system byte ordering ... little endian
checking for size_t size ... 8 bytes
checking for off_t size ... 8 bytes
checking for time_t size ... 8 bytes
checking for setproctitle() ... not found
checking for pread() ... found
checking for pwrite() ... found
checking for pwritev() ... found
checking for sys_nerr ... found
checking for localtime_r() ... found
checking for posix_memalign() ... found
checking for memalign() ... found
checking for mmap(MAP_ANON|MAP_SHARED) ... found
checking for mmap("/dev/zero", MAP_SHARED) ... found
checking for System V shared memory ... found
checking for POSIX semaphores ... not found
checking for POSIX semaphores in libpthread ... found
checking for struct msghdr.msg_control ... found
checking for ioctl(FIONBIO) ... found
checking for struct tm.tm_gmtoff ... found
checking for struct dirent.d_namlen ... not found
checking for struct dirent.d_type ... found
checking for sysconf(_SC_NPROCESSORS_ONLN) ... found
checking for openat(), fstatat() ... found
checking for getaddrinfo() ... found
checking for PCRE library ... found
checking for PCRE JIT support ... found
checking for md5 in system md library ... not found
checking for md5 in system md5 library ... not found
checking for md5 in system OpenSSL crypto library ... found
checking for sha1 in system md library ... not found
checking for sha1 in system OpenSSL crypto library ... found
checking for zlib library ... found
creating objs/Makefile

Configuration summary
  + using system PCRE library
  + OpenSSL library is not used
  + md5: using system crypto library
  + sha1: using system crypto library
  + using system zlib library

  nginx path prefix: "/usr/local/nginx"
  nginx binary file: "/usr/local/nginx/sbin/nginx"
  nginx configuration prefix: "/usr/local/nginx/conf"
  nginx configuration file: "/usr/local/nginx/conf/nginx.conf"
  nginx pid file: "/usr/local/nginx/logs/nginx.pid"
  nginx error log file: "/usr/local/nginx/logs/error.log"
  nginx http access log file: "/usr/local/nginx/logs/access.log"
  nginx http client request body temporary files: "client_body_temp"
  nginx http proxy temporary files: "proxy_temp"
  nginx http fastcgi temporary files: "fastcgi_temp"
  nginx http uwsgi temporary files: "uwsgi_temp"
  nginx http scgi temporary files: "scgi_temp"

then I have ran separate test case folder an ran it 

 TEST_NGINX_BINARY=/path/to/nginx/objs/nginx prove . > test_status

output was  test_status

./access.t ............................. skipped: no ipv6 available
./access_log.t .........................
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/10 subtests
./access_log_variables.t ............... ok
./addition.t ........................... ok
./auth_basic.t .........................
Dubious, test returned 14 (wstat 3584, 0xe00)
Failed 14/22 subtests
./auth_request.t .......................
Dubious, test returned 8 (wstat 2048, 0x800)
Failed 8/20 subtests
        (less 2 skipped subtests: 10 okay)
./auth_request_satisfy.t ...............
Dubious, test returned 6 (wstat 1536, 0x600)
Failed 6/19 subtests
./auth_request_set.t ...................
Dubious, test returned 4 (wstat 1024, 0x400)
Failed 4/7 subtests
./autoindex.t ..........................
Dubious, test returned 15 (wstat 3840, 0xf00)
Failed 15/17 subtests
./autoindex_format.t ...................
Dubious, test returned 33 (wstat 8448, 0x2100)
Failed 33/38 subtests
./body.t ...............................
Dubious, test returned 6 (wstat 1536, 0x600)
Failed 6/14 subtests
./body_chunked.t .......................
Dubious, test returned 4 (wstat 1024, 0x400)
Failed 4/11 subtests
./charset.t ............................
Dubious, test returned 5 (wstat 1280, 0x500)
Failed 5/8 subtests
./charset_gzip_static.t ................ skipped: no gzip_static available
./config_dump.t ........................ ok
./dav.t ................................
Dubious, test returned 14 (wstat 3584, 0xe00)
Failed 14/16 subtests
./dav_chunked.t ........................
Dubious, test returned 2 (wstat 512, 0x200)
Failed 6/7 subtests
./debug_connection.t ................... skipped: no --with-debug available
./debug_connection_syslog.t ............ skipped: no --with-debug available
./empty_gif.t .......................... ok
./error_log.t .......................... ok
./fastcgi.t ............................ skipped: FCGI not installed
./fastcgi_body.t ....................... skipped: FCGI not installed
./fastcgi_body2.t ...................... skipped: FCGI not installed
./fastcgi_buffering.t .................. skipped: FCGI not installed
./fastcgi_cache.t ...................... skipped: FCGI not installed

./fastcgi_header_params.t .............. skipped: FCGI not installed
./fastcgi_keepalive.t .................. ok
./fastcgi_merge_params.t ............... skipped: FCGI not installed
./fastcgi_merge_params2.t .............. skipped: FCGI not installed
./fastcgi_request_buffering.t .......... skipped: FCGI not installed
./fastcgi_request_buffering_chunked.t .. skipped: FCGI not installed
./fastcgi_split.t ...................... skipped: FCGI not installed
./fastcgi_variables.t .................. skipped: FCGI not installed
./geo.t ................................ skipped: no 127.0.0.1 on host
./gunzip.t ............................. skipped: no gzip_static available
./gunzip_memcached.t ................... skipped: Cache::Memcached not installed
./gunzip_perl.t ........................ ok
./gunzip_ssi.t ......................... skipped: no gzip_static available
./gunzip_static.t ...................... skipped: no gzip_static available
./gzip.t ...............................
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/9 subtests
./gzip_flush.t ......................... ok
./h2.t ................................. skipped: IO::Socket::SSL not installed
./headers.t ............................
Dubious, test returned 16 (wstat 4096, 0x1000)
Failed 16/26 subtests
./http_disable_symlinks.t .............. skipped: no external file found
./http_error_page.t ....................
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/8 subtests
./http_expect_100_continue.t ........... ok
./http_host.t .......................... ok
./http_location.t ...................... ok
./http_location_auto.t ................. ok
./http_location_win32.t ................ skipped: not win32
./http_resolver.t ...................... ok
./http_resolver_aaaa.t ................. skipped: no ipv6 available
./http_server_name.t ...................
Dubious, test returned 19 (wstat 4864, 0x1300)
Failed 19/21 subtests
./http_try_files.t .....................
Dubious, test returned 5 (wstat 1280, 0x500)
Failed 5/11 subtests
./http_variables.t ..................... ok
./image_filter.t ....................... skipped: GD not installed
./image_filter_finalize.t ..............
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/4 subtests
./index.t ..............................
Dubious, test returned 5 (wstat 1280, 0x500)
Failed 5/8 subtests
./js.t ................................. skipped: no njs available
./limit_conn.t .........................
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/9 subtests

Dubious, test returned 5 (wstat 1280, 0x500)
Failed 5/8 subtests
./js.t ................................. skipped: no njs available
./limit_conn.t .........................
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/9 subtests
./limit_conn_complex.t ................. ok
./limit_req.t ..........................
Dubious, test returned 3 (wstat 768, 0x300)
Failed 3/6 subtests
./mail_error_log.t ..................... ok
./mail_imap.t .......................... ok
./mail_imap_ssl.t ...................... skipped: IO::Socket::SSL not installed
./mail_pop3.t .......................... ok
./mail_resolver.t ...................... ok
./mail_smtp.t .......................... ok
./mail_smtp_greeting_delay.t ........... ok
./mail_smtp_xclient.t .................. ok
./map.t ................................ ok
./memcached.t .......................... skipped: Cache::Memcached not installed
./memcached_fake.t .....................
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/4 subtests
./memcached_keepalive.t ................ skipped: Cache::Memcached not installed
./memcached_keepalive_stale.t .......... skipped: Cache::Memcached not installed
./mp4.t ................................ skipped: no mp4 available
./not_modified.t .......................
Dubious, test returned 13 (wstat 3328, 0xd00)
Failed 13/16 subtests
        (less 2 skipped subtests: 1 okay)
./not_modified_proxy.t .................
Dubious, test returned 12 (wstat 3072, 0xc00)
Failed 12/13 subtests
./perl.t ............................... ok
./perl_gzip.t .......................... ok
./post_action.t ........................
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/6 subtests
./proxy.t .............................. ok
./proxy_bind.t .........................
Dubious, test returned 4 (wstat 1024, 0x400)
Failed 4/5 subtests
./proxy_cache.t ........................
Dubious, test returned 11 (wstat 2816, 0xb00)
Failed 11/14 subtests
./proxy_cache_chunked.t ................
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/3 subtests
./proxy_cache_convert_head.t ...........
                                                 

./range_charset.t ......................
Dubious, test returned 10 (wstat 2560, 0xa00)
Failed 10/11 subtests
./range_flv.t ..........................
Dubious, test returned 12 (wstat 3072, 0xc00)
Failed 12/13 subtests
./range_if_range.t .....................
Dubious, test returned 7 (wstat 1792, 0x700)
Failed 7/9 subtests
./range_mp4.t .......................... skipped: no mp4 available
./realip.t ............................. skipped: no 127.0.0.1 on host
./realip_remote_addr.t ................. skipped: no 127.0.0.1 on host
./referer.t ............................ ok
./rewrite.t ............................
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/23 subtests
./rewrite_set.t ........................ ok
./rewrite_unescape.t ................... ok
./scgi.t ............................... skipped: SCGI not installed
./scgi_body.t .......................... skipped: SCGI not installed
./scgi_cache.t ......................... skipped: SCGI not installed
./scgi_gzip.t .......................... skipped: SCGI not installed
./scgi_merge_params.t .................. skipped: SCGI not installed
./secure_link.t ........................
Dubious, test returned 6 (wstat 1536, 0x600)
Failed 6/11 subtests
./spdy.t ............................... skipped: no spdy available
./split_clients.t ......................
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests
./ssi.t ................................
Dubious, test returned 19 (wstat 4864, 0x1300)
Failed 19/28 subtests
./ssi_if.t .............................
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run
./ssi_include_big.t ....................
Dubious, test returned 4 (wstat 1024, 0x400)
Failed 4/9 subtests
./ssi_waited.t .........................
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests
./ssl.t ................................ skipped: IO::Socket::SSL not installed
./ssl_certificate_chain.t .............. skipped: IO::Socket::SSL not installed
./ssl_engine_keys.t .................... skipped: may not work, leaves coredump
./ssl_password_file.t .................. skipped: IO::Socket::SSL not installed
./ssl_proxy_protocol.t ................. skipped: IO::Socket::SSL not installed
./ssl_proxy_upgrade.t .................. skipped: IO::Socket::SSL not installed
./ssl_sni.t ............................ skipped: IO::Socket::SSL version >= 1.56 required
                                                                                                                        
Test Summary Report
-------------------
./access_log.t                       (Wstat: 512 Tests: 8 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 10 tests but ran 8.
./auth_basic.t                       (Wstat: 3584 Tests: 22 Failed: 14)
  Failed tests:  2, 4, 6-10, 15-21
  Non-zero exit status: 14
./auth_request.t                     (Wstat: 2048 Tests: 20 Failed: 8)
  Failed tests:  1, 5-6, 8, 12, 15-17
  Non-zero exit status: 8
./auth_request_satisfy.t             (Wstat: 1536 Tests: 19 Failed: 6)
  Failed tests:  1, 10-13, 16
  Non-zero exit status: 6
./auth_request_set.t                 (Wstat: 1024 Tests: 7 Failed: 4)
  Failed tests:  1-4
  Non-zero exit status: 4
./autoindex.t                        (Wstat: 3840 Tests: 17 Failed: 15)
  Failed tests:  1-4, 6-16
  Non-zero exit status: 15
./autoindex_format.t                 (Wstat: 8448 Tests: 38 Failed: 33)
  Failed tests:  1-8, 10, 12-24, 26-27, 29-37
  Non-zero exit status: 33
./body.t                             (Wstat: 1536 Tests: 14 Failed: 6)
  Failed tests:  4-5, 7-8, 11-12
  Non-zero exit status: 6
./body_chunked.t                     (Wstat: 1024 Tests: 11 Failed: 4)
  Failed tests:  3-4, 6-7
  Non-zero exit status: 4
./charset.t                          (Wstat: 1280 Tests: 8 Failed: 5)
  Failed tests:  2-4, 6-7
  Non-zero exit status: 5
./dav.t                              (Wstat: 3584 Tests: 16 Failed: 14)
  Failed tests:  1-7, 9-15
  Non-zero exit status: 14
./dav_chunked.t                      (Wstat: 512 Tests: 2 Failed: 1)
  Failed test:  1
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 7 tests but ran 2.
./gzip.t                             (Wstat: 512 Tests: 9 Failed: 2)
  Failed tests:  2, 4
  Non-zero exit status: 2
./headers.t                          (Wstat: 4096 Tests: 26 Failed: 16)
  Failed tests:  1-2, 7-8, 10-16, 18-22
  Non-zero exit status: 16
./http_error_page.t                  (Wstat: 256 Tests: 8 Failed: 1)
  Failed test:  6
  Non-zero exit status: 1
./http_server_name.t                 (Wstat: 4864 Tests: 21 Failed: 19)
  Failed tests:  1, 3-20
  Non-zero exit status: 19

**Comment by mangeshPSL** [comment]
Please anyone help me out

**Comment by csanders-git** [comment]
Are you having problems with nginx or modsecurity?

**Comment by mangeshPSL** [comment]
test case of nginx

**Comment by zimmerle** [comment]
Hi @mangeshPSL,

Those are known errors on the "release" version of Nginx. We are currently working with "libmodsecurity"  and "ModSecurity nginx connector". This ModSecurity-nginx connector not only pass in the most of the tests, but contains nginx-compatible test for its own:

https://github.com/SpiderLabs/ModSecurity-nginx/tree/master/tests

Here is the link with our QA, running the very same tests that you have run:
- http://www.modsecurity.org/developers/buildbot/modsecurity-nginx/builders/Linux32%20-%20Nginx%20%28Mainline%29/builds/11/steps/nginx%20tests%20%28modsecurity%20off%3B%20modsecurity_rules%20%22SecRuleEngine%20On%3B%22%29/logs/stdio

For all tests: 
- http://www.modsecurity.org/developers/buildbot/modsecurity-nginx/waterfall

For more information on libmodsecurity:
- https://github.com/SpiderLabs/ModSecurity/tree/libmodsecurity/

And/or ModSecurity-nginx connector:
- https://github.com/SpiderLabs/ModSecurity-nginx/

**Comment by mangeshPSL** [comment]
Thanks zimmerle ,
           but can you provide me some stuff so that I can build nginx from source code and also steps to build it and test cases , which can test nginx.  some url , links.
or documentation . I tried several way but failed .

**Comment by zimmerle** [comment]
Hi @mangeshPSL,

The first step is to compile the libmodsecurity, instructions are available here:
- https://github.com/SpiderLabs/ModSecurity/tree/libmodsecurity/#compilation

The second step will be to compile the Nginx-connector:
- https://github.com/SpiderLabs/ModSecurity-nginx#compilation

Once you have those two projects compiled and installed, you can use the prove utility. You can run in the same way that you run the tests without ModSecurity.
