### ISSUE TITLE
nginx -t failing for higher number of domains

### ISSUE THREAD

**Issue by AnoopAlias** [SpiderLabs/ModSecurity-nginx#42]
I am testing ModSecurity-nginx and i have 

```
server{
modsecurity on;
location / {
modsecurity_rules_file /etc/nginx/conf.d/zz_modsecurity.conf;
}
}
```

Towards the end of /etc/nginx/conf.d/zz_modsecurity.conf file i added
```
# Include OWASP crs core ruleset
Include /etc/nginx/owasp-modsecurity-crs/crs-setup.conf
Include /etc/nginx/owasp-modsecurity-crs/rules/*.conf

```
I am not sure if this is how it should be done . Because this works fine for a few domains (3-4 nos). But when we add say like 30 domains.

nginx -t itself is failing and taking long time to complete and consume all memory on low memory server

```
# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: [alert] mmap(MAP_ANON|MAP_SHARED, 335544320) failed (12: Cannot allocate memory)
nginx: configuration file /etc/nginx/nginx.conf test failed

```

What am I doing wrong? . If I am doing everything fine then I believe the large file inclusion is making it harder for config test and loading of config file for nginx . even with somthing like 30-40 domains added.

**Comment by AnoopAlias** [comment]
modsecurity_rules_file is valid in the server context too (but the doc says to put it in location context). 
I had put it in 2 locations per server. Now i removed it and put it outside location block (only once per server in this case ) 

Even now nginx -t is consuming a lot of time to finish. I guess it needs to loop through all the crs file for each server?.

Following is the time taken for 36 domains in a 2 GB KVM vps
```
# time nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

real	0m23.287s
user	0m22.147s
sys	0m0.863s
```

I am sure this will be almost on a very big scale for servers hosting 500+ domains.

**Comment by zimmerle** [comment]
Hi @AnoopAlias,

any reason why not to use the configuration in the global (http) section ?

**Comment by AnoopAlias** [comment]
@zimmerle - Ok putting this in the http context works. I was just following the docs which mention about putting the rules file in location context. 

So I guess the best way to do this put 
```
modsecurity on;
modsecurity_rules_file /etc/nginx/conf.d/zz_modsecurity.conf;

```
in the http context and for vhost's that dont need mod_sec put

`modsecurity off;
`
in the server section
?

**Comment by zimmerle** [comment]
That would be a good idea :)

Tell me if you face any problems.

**Comment by intelbg** [comment]
@zimmerle I have the same problem here. Stopped the groups, increased sh.min and sh.memmax in /etc/sysctl.conf but nginx does not start again. I use mosecurity on in the server { block, but not in http because I don't want modsec to be turned for all customers, every customer has a user.conf.

**Comment by AnoopAlias** [comment]
@intelbg - if you set modsecurity off; in the server {} context it dosnt work for the vhost ,so is fine.

**Comment by intelbg** [comment]
@AnoopAlias the problem exists even if mod security directive is not present on the vhosts. I created another post for that - even when modsec does not work work for the vhosts , only compiled in the nginx binary it has memory allocation problems and servers loads on 150+ immediately after nginx configtest or restart. Without modsec there isn't a problems.
