### ISSUE TITLE
Won't compile with nginx 1.12.0

### ISSUE THREAD

**Issue by JSkier21** [SpiderLabs/ModSecurity-nginx#46]
I can't seem to get this connector to compile with nginx 1.12.0

I have installed modsecurity lib but when I compile nginx, it claims it can't find it.

Output:
```
adding module in /opt/ModSecurity-nginx
checking for ModSecurity library ... not found
checking for ModSecurity library in /usr/local/modsecurity ... not found
 ./configure: error: ngx_http_modsecurity_module requires the ModSecurity library.
```

tree command of /usr/local/modsecurity:

> /usr/local/modsecurity/
> ├── bin
> │   ├── mlogc
> │   ├── mlogc-batch-load.pl
> │   └── rules-updater.pl
> └── lib
>     └── mod_security2.so

Did I not compile the branch for the modsecurity library correctly? Perhaps I missed something. 

EDIT: For instructions on the library compilation, I went here (however I'm using different VPS and ArchLinux):
[https://help.dreamhost.com/hc/en-us/articles/223608748-How-to-Install-libmodsecurity-Nginx-on-Ubuntu-14-04](url)

**Comment by Stanback** [comment]
@JSkier21 I had the same problem initially. You'll need to checkout the `v3/master` branch of https://github.com/SpiderLabs/ModSecurity to build `libmodsecurity` prior to compiling nginx. I found the recipes here to be helpful: https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes

**Comment by zimmerle** [comment]
Hi @JSkier21,

What you have compiled was ModSecurity version 2. For this nginx connector you need to have the ModSecurity version 3. You can find some compilations receipts here:
https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes

**Comment by JSkier21** [comment]
Thanks, I was able to get the recipes up and it seems be good.
