### ISSUE TITLE
Issues while using error_page and location

### ISSUE THREAD

**Issue by zimmerle** [SpiderLabs/ModSecurity-nginx#55]
According to the original report (Ehsan Mahdavi) the audit logs are not working for custom error pages (using: **error_page** or **location**). In that scenario the logs are not written.

Ehsan Mahdavi also said that in case of SecRuleEngine is set to DetectionOnly everything works like expected.

**Comment by intelbg** [comment]
Hello, is there a plan to be fixed? The issue still exists and it's very serious. Also, audit_logging now works without the custom 403 page only in serial mode, not in concurrent. Thank you in advance. I think fixing this will solve many other issues and will help many people like me.

**Comment by intelbg** [comment]
In addition, the problem with concurrent logging was my mistake. It works. Remains the problem with custom 403 page only.

**Comment by intelbg** [comment]
If you don't plan to fix it can you please tell me which file and function is related to this problem ?

**Comment by victorhora** [comment]
@averges @intelbg 

Have you tried enabling the intercept_errors directives (e.g. [proxy_intercept_errors](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_intercept_errors)) directive in Nginx?

**Comment by intelbg** [comment]
hi @victorhora! Thanks about the reply. I tried - in server block and in location. but didn't help. Logging didn't work with it too with custom 403 page.

**Comment by averges** [comment]
@victorhora, yes, I've tried with intercept_errors directives but no luck.

Thank you for looking into this error.

**Comment by ceasbz** [comment]
@zimmerle Here too

It's enabled the `proxy_intercept_errors` and returns the same problem.

**Comment by ceasbz** [comment]
Maybe, have some problem in this code: https://github.com/SpiderLabs/ModSecurity-nginx/blob/master/src/ngx_http_modsecurity_module.c#L164-L186

I'm trying to understand it

**Comment by intelbg** [comment]
@ceasbz I think that the problem is in this chunk of code too, but I a can't understand and fix it. If you do it please share the fix. I will appreciate it!

**Comment by zimmerle** [comment]
Hi,

Notice the configurations [[1](https://gist.github.com/zimmerle/41ccae419386f5164cea95ac7f78e02b)] and [[2](https://gist.github.com/zimmerle/a5574df6a76e8b5a7d625c36225dc9b4)]. They are different by the error_block location.

In [[1](https://gist.github.com/zimmerle/41ccae419386f5164cea95ac7f78e02b)] the _error_ was specified inside the _location block_. In that case the ModSecurity rules specified for the location block will be also applied to the _error_. That is different from [[2](https://gist.github.com/zimmerle/41ccae419386f5164cea95ac7f78e02b)] where we have no ModSecurity rules configured for the _error block._

In my tests, having the configuration in the right place, I managed to have ModSecurity working as expected. I am closing the bug assuming that it was a configuration issue. If you think otherwise, please re-open.

**Comment by rm3nchaca** [comment]
Hi!
I've tested the 2 example configs, the 1 is not showing the custom error page but is logging as expected, the 2 displays the custom error page but is not logging.

**Comment by AirisX** [comment]
Hi @rm3nchaca,

Try to consider suggestions in this thread  https://github.com/SpiderLabs/ModSecurity-nginx/issues/76

**Comment by intelbg** [comment]
Hello @AirisX! I replaced the files with yours and recompiled nginx with the new modsecurity-nginx files. Logging seems to work, but uid parameter is no more logged in the audit log. UID parameter is a uid cookie set in nginx with userid module like follows:

 userid on;
    userid_name uid;
    userid_expires 1s;
    userid_path /;
Then when you are blocked on the page it's shown:
403 Forbidden by TU2Xb1qNgCOsXwgwAwMDAg==

And this should be logged in audit logs too as it was before your patch. Can you please give me an advice how to proceed?

**Comment by AirisX** [comment]
Hello @intelbg,

Could you provide your config? Please, also show an example of the audit log entries before and after patch.

**Comment by intelbg** [comment]
@AirisX Thank you about your reply!
Here is the config file, the log file now and screenshot of log file before the patch where there is a line cookie with the uid value. Do you think that this is related to the patch? If you prefer I can write you on a private message/email.

[config.txt](https://github.com/SpiderLabs/ModSecurity-nginx/files/1750938/config.txt)
[log_after_patch.txt](https://github.com/SpiderLabs/ModSecurity-nginx/files/1750940/log_after_patch.txt)
![screen shot 2017-08-12 at10 10 56 am](https://user-images.githubusercontent.com/12134584/36585243-c02ecfa0-1885-11e8-9f2b-527464828eed.png)

**Comment by AirisX** [comment]
Hello @intelbg, 

Could you clarify, do you mean `uid` cookie in the request header? As I can see from you screenshot of the log file, you are talking about request header. In this case this may be due to the parameter `userid_expires` which sets the expiration time to `1s` and the next client request after this time may not contain this cookie. Therefore, if you make 2 (or more) requests per second the second and subsequent audit entries will contain the `uid` cookie.

**Comment by intelbg** [comment]
@AirisX you are right! But no matter what value it's set in some moment there is a point that no uid cookie is logged and I can't understand why. In the time of expiration it should provide and log immediately a different cookie, right?

**Comment by AirisX** [comment]
@intelbg Yes, while the `uid` cookie is not expired, it should be logged. Try to increase the `userid_expires` value to 1 hour, to exclude other reasons.

**Comment by intelbg** [comment]
@AirisX even with 1 hour settings for expiration, the first request for example does not log the uid cookie. With the second and third there is no problem (I attached the log).
[auditlog.txt](https://github.com/SpiderLabs/ModSecurity-nginx/files/1774513/auditlog.txt)
Also, if it's with big expiration time one uid cookie will match / parse more than one matched/blocked rule as I want to have separate uid cookie value for every different block hit. How can achive it? Is it possible and why in case of expiration it's not logged as it should immediately assign another uid cookie hash. Sorry it it's already out of the topic but technically I really can't understand this and need solution.

**Comment by logopk** [comment]
I still have the issue today. Custom error Page:
        error_page  403              /custom_403.html; #<< contains only "Forbidden"
        location = /custom_403.html {
                root /usr/share/nginx/html;
                internal;
        }
I have tried to do the modsec-block before and after the custom error page...

Modsecurity shows the Default ErrorPage,
Logging does work fine

nginx 1.13.10
modsec v3/master
ModSecurity-nginx HEAD
