### ISSUE TITLE
Jump on uninitialized values

### ISSUE THREAD

**Issue by LinuxJedi** [SpiderLabs/ModSecurity-nginx#6]
The data element of the string variables in the configuration is unset at initialize time. This can cause startup failure in NGINX for certain allocators. You can reproduce this with the following when daemon and master_process is disabled in NGINX:

```
valgrind --malloc-fill=A5 --free-fill=DE sbin/nginx
```

I've attached a patch for this
[conf_fix.diff.zip](https://github.com/SpiderLabs/ModSecurity-nginx/files/132784/conf_fix.diff.zip)

**Comment by zimmerle** [comment]
Hi @LinuxJedi,

Thanks for the patch. It was merged into our master tree.
