### ISSUE TITLE
Have ModSecurity-nginx variable in nginx?

### ISSUE THREAD

**Issue by patsevanton** [SpiderLabs/ModSecurity-nginx#60]
Hello.
Have ModSecurity-nginx variable in nginx?
Can i used this code?
if ($modsecurity variable) {
  modsecurity_rules '
    SecRuleRemoveById 10 ';
}

if ($modsecurity variable) {
    modsecurity on;
    modsecurity_rules_file /etc/nginx/main.conf;
}

If nginx made with modsecurity than block modsecurity_rules work.
If nginx made without modsecurity than block modsecurity_rules does not work.

Can you help me?

**Comment by victorhora** [comment]
Hi @patsevanton,

I'm not sure if I'm getting 100% what you're trying to do. Maybe you're trying to add this "if" condition inside your nginx.conf to have ModSecurity enabled based on an externally set variable (set by a request or another program?)

You're trying to use the [If condition of ngx_http_rewrite_module](https://nginx.org/en/docs/http/ngx_http_rewrite_module.html#if)?

**Comment by patsevanton** [comment]
What modsec variable i can use?

Examples from link:
```
if ($http_user_agent ~ MSIE) {
    rewrite ^(.*)$ /msie/$1 break;
}

if ($http_cookie ~* "id=([^;]+)(?:;|$)") {
    set $id $1;
}

if ($request_method = POST) {
    return 405;
}

if ($slow) {
    limit_rate 10k;
}

if ($invalid_referer) {
    return 403;
}
```
Thank for answer

**Comment by zimmerle** [comment]
Hi @patsevanton,

ModSecurity does not export back to nginx any of its internal variables. However, you can use environment variables establish a communication between ModSecurity and other process.
