### ISSUE TITLE
RESPONSE_BODY not work when using proxy_module

### ISSUE THREAD

**Issue by friparia** [SpiderLabs/ModSecurity-nginx#61]
Original Issue: https://github.com/SpiderLabs/ModSecurity/issues/1520

The reason is that when using proxy, variable `buffer_fully_loadead` cannot be assigned to 1, so it cannot execute the modsecurity functions.

In my project, I just delete this variable and it works fine with me, but I don't know whether it has the side effect or some other bugs.

**Comment by azurit** [comment]
I'm not able to match RESPONSE_BODY even using ctl:ruleRemoveTargetById (so it cannot be excluded).

**Comment by Sodium-Hydrogen** [comment]
Any progress on this?

**Comment by amsnek** [comment]
hmm response body seems to be processed, modsecurity claims to throw 403 but requests gets through? i assume this wonr be fixed anymore? 
@Sodium-Hydrogen what did you mean it worked for you but mime type was not set? for me, php leakage gets through to client, mime type on response seems correct though 🤔
