### ISSUE TITLE
nginx config syntax valdation takes long when modsecurity is set on

### ISSUE THREAD

**Issue by AnoopAlias** [SpiderLabs/ModSecurity-nginx#67]
This is related to #42 as I can confirm that modsec config loaded (even in http context ) with a large number of server {} blocks will makenginx config test and start take very long that is impossible to load mod_security v3 in nginx on typically shared hosts who hold 500+ domains on a server.

Not sure if this is issue with nginx and must be discussed in nginx dev-list or SpiderLabs/ModSecurity-nginx . All I can say is that at present only mod_sec v3 seem to cause such issues( probably due to the large number of rules parsed and I have a doubt that even if the rules are in http{} context ,it somehow causes the configs to be replicated in the server {} context too even if we just specify 

modsecurity on;

in the server context.

**Comment by intelbg** [comment]
Hi, I think that the problem I reported and the people from mod security provided me a patch for this is the same as mine. Please read this post and apply the patch memory.zip:

https://github.com/SpiderLabs/ModSecurity/issues/1563

Do you experience the problem also when modsecurity is not on?

**Comment by zimmerle** [comment]
Fixed at SpiderLabs/ModSecurity#1563
