### ISSUE TITLE
ctl:ruleEngine=off not being supported

### ISSUE THREAD

**Issue by feanorknd** [SpiderLabs/ModSecurity-nginx#69]
Hello:

Several ctl actions are not being supported nowadays, but this one is now supported by libmodsecurity.

https://github.com/SpiderLabs/ModSecurity/issues/1495
https://github.com/SpiderLabs/ModSecurity/commit/4bec6b001902033c43537710d548d731048af210

But if try to use, just nginx config test gives:

`"modsecurity_rules_file" directive Rules error.`

Thanks so much for your work!

**Comment by zimmerle** [comment]
Hi @feanorknd,

Do you mind to share the entire error message? I am afraid that you are not receiving an error because of  _ctl:ruleEngine=off_, as it appears to be working as expected.
