### ISSUE TITLE
The modsecurity_rules_file directive doesn't work with relative path

### ISSUE THREAD

**Issue by sgplay** [SpiderLabs/ModSecurity-nginx#70]
The modsecurity_rules_file directive doesn't work with relative path.
modsecurity_rules_file     modsecurity.conf;

nginx -t
nginx: [emerg] "modsecurity_rules_file" directive Failed to open the file: modsecurity.conf

The full path works fine.

The issue prevent to prepare the same vhost  conf file for different OS platforms:
If nginx home located on different path. For example:
/etc/nginx/modsecurity.conf
/usr/local/etc/nginx/modsecurity.conf

Thank you in advance.

**Comment by zimmerle** [comment]
The loading of the configuration is now relative, considering the following schema:

 - Is it on the current folder or relative to it?
 - Is it a full path?
 - Does it uses wildcards, if so, expand.
 - Is it in the same folder of the current configuration or relative to it?

**Comment by martinhsv** [comment]
Hi @InoryS ,

I don't have any direct knowledge of the asserted implementation of this enhancement as it was well before my involvement with the project.

I do agree that the current functionality does not appear to support using relative paths -- at least not in the way you mean.

The code looks like it will use a relative path, but it would be relative to the current working directory of the process in question -- which by default is '/'.  In your case for, example, it might still work if you removed the beginning '/' character from the file path that you specified.

In any case, I would recommend using an absolute path.
