### ISSUE TITLE
assembly problem through rpmbuild on centos

### ISSUE THREAD

**Issue by psymanik** [SpiderLabs/ModSecurity-nginx#9]
We are observing the assembly problem through RPM build.  Please tell me pless what's wrong? 
`ERROR   0002: file '/usr/sbin/nginx' contains an invalid rpath '/usr/local/modsecurity/lib' in [/usr/local/modsecurity/lib]`
`ERROR   0002: file '/usr/sbin/nginx.debug' contains an invalid rpath '/usr/local/modsecurity/lib' in [/usr/local/modsecurity/lib]`

**Comment by zimmerle** [comment]
Hi @psymanik,

Do you mind to try to install the library in the /usr folder, instead of /usr/local?

I think that is the main issue.
