### ISSUE TITLE
This error I have when try to build libmodsecurity

### ISSUE THREAD

**Issue by petarkozic** [SpiderLabs/ModSecurity-nginx#95]
On Ubuntu 16.04
this is prerequisites which is installed:

`apt-get install apache2-dev autoconf automake build-essential bzip2 checkinstall devscripts flex g++ gcc git graphicsmagick-imagemagick-compat graphicsmagick-libmagick-dev-compat libaio-dev libaio1 libass-dev libatomic-ops-dev libavcodec-dev libavdevice-dev libavfilter-dev libavformat-dev libavutil-dev libbz2-dev libcdio-cdda1 libcdio-paranoia1 libcdio13 libcurl4-openssl-dev libfaac-dev libfreetype6-dev libgd-dev libgeoip-dev libgeoip1 libgif-dev libgpac-dev libgsm1-dev libjack-jackd2-dev libjpeg-dev libjpeg-progs libjpeg8-dev liblmdb-dev libmp3lame-dev libncurses5-dev libopencore-amrnb-dev libopencore-amrwb-dev libpam0g-dev libpcre3 libpcre3-dev libperl-dev libpng12-dev libpng12-0 libpng12-dev libreadline-dev librtmp-dev libsdl1.2-dev libssl-dev libssl1.0.0 libswscale-dev libtheora-dev libtiff5-dev libtool libva-dev libvdpau-dev libvorbis-dev libxml2-dev libxslt-dev libxslt1-dev libxslt1.1 libxvidcore-dev libxvidcore4 libyajl-dev make openssl perl pkg-config tar texi2html unzip zip zlib1g-dev`

I tried with this steps:
$ cd /opt/ 
$ git clone https://github.com/SpiderLabs/ModSecurity 
$ cd ModSecurity 
$ git checkout -b v3/master origin/v3/master 
$ sh build.sh 
$ git submodule init 
$ git submodule update 
$ ./configure 
$ make
$ make install

After `make` I get this error:

`/opt/ModSecurity/src/variables/xml.cc:83: undefined reference to `xmlXPathNewContext'
/opt/ModSecurity/src/variables/xml.cc:99: undefined reference to `xmlXPathRegisterNs'
/opt/ModSecurity/src/variables/xml.cc:127: undefined reference to `xmlXPathFreeObject'
/opt/ModSecurity/src/variables/xml.cc:146: undefined reference to `xmlXPathFreeContext'
/opt/ModSecurity/src/variables/xml.cc:116: undefined reference to `xmlXPathEvalExpression'
/opt/ModSecurity/src/variables/xml.cc:142: undefined reference to `xmlFree'
/opt/ModSecurity/src/variables/xml.cc:135: undefined reference to `xmlNodeGetContent'
collect2: error: ld returned 1 exit status
Makefile:540: recipe for target 'modsec-rules-check' failed
make[2]: *** [modsec-rules-check] Error 1
make[2]: Leaving directory '/opt/ModSecurity/tools/rules-check'
Makefile:477: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/opt/ModSecurity/tools'
Makefile:954: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1`

**Comment by victorhora** [comment]
Duplicate with https://github.com/SpiderLabs/ModSecurity/issues/1685.

Issue was fixed as of https://github.com/SpiderLabs/ModSecurity/commit/854a661a2a86357326b5c6be9799e9ab943b61e3
